### ISSUE TITLE
[XP Cannes] - Dispositif Clef Verte (financement Région Sud)

### ISSUE THREAD

**Issue by RodolpheGagetta** [betagouv/mission-transition-ecologique#1003]
```[tasklist]
### Tasks
- [x] Point avec la Clef Verte le 25/09
- [x] Valider auprès Région Sud mise en avant
- [x] Ecriture du dispositif
```

**Comment by mpiac** [comment]
@ColineLebaratoux Je peux te laisser jeter un coup d'oeil ? J'ai repris pas mal d'élément de la fiche déjà existante audit clef verte qui porte un peu à confusion et pour laquelle je dois faire des propositions de refonte. C'est la fiche 298 : audit clef verte sud.

**Comment by mpiac** [comment]
@ttdm Coucou Thibaut ! Peut-on publier ce dispositif ? La review a été faite de notre côté, je te laisse regarder si tu vois des choses :)
