### ISSUE TITLE
[XP Cannes] - Ajout des dispositifs Agglo

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#1006]
```[tasklist]
### Tasks
- [ ] Collecte biodéchet (accompagnement pendant 1h) (lien vers le typeform ajout dispositif envoyé)
- [ ] Etude du potentiel solaire (lien typeforme ajout dispositif envoyé)
- [x] Relance étude potentiel solaire le 04/09 et collecte biodéchet
```

**Comment by mpiac** [comment]
N'ont pas statué sur ces dispositifs à date.
