### ISSUE TITLE
[XP Cannes] - Présentation de TEE à l'assemblée "Force Locale Décarbonnée" en présence d'élus et d'entrepreneurs

### ISSUE THREAD

**Issue by RodolpheGagetta** [betagouv/mission-transition-ecologique#1017]
Pitch du service (10 minutes) en présence d'élus et d'entrepreneurs+ rencontres avec les entrepreneurs de la Force Locale Décarbonnée.
19 Septembre de 9h à 11h
```[tasklist]
### Tasks
- [x] Préparation de la présentation (Pitch, repétitions)
- [x] Préparation des visuels (récupération des formats)
- [x] Réservation des VHR
```

**Comment by mpiac** [comment]
Point le vendredi 6 avec Cap'Ther pour une présentation croisée : https://docs.google.com/presentation/d/1gDWb1MSDjmrNafZOg3_cbjaCvnEfA-aqvHvCtyDUYao/edit#slide=id.g2fb33e4ae1d_0_0
