### ISSUE TITLE
[XP Cannes] - Salon International du Tourisme - 5 & 6 octobre 2024

### ISSUE THREAD

**Issue by RodolpheGagetta** [betagouv/mission-transition-ecologique#1018]
Participation au [Salon International du Tourisme](https://www.cannes.com/fr/agenda/annee-2024/octobre/salon-international-du-tourisme.html) de Cannes

Présentation du service au partenaire Radio Cannes (Interview annonçant la présence du service sur le Salon)

Pitch + Speed-meetings avec les entreprises sur place, notamment la responsable du syndicat des hôteliers, C. WELTER et Noémie DEWAVRIN, Hotelière et conseillère municipale
```[tasklist]
### Tasks
- [x] Réservation du stand
- [ ] Reservation des VHR
- [ ] Création des habillages (Kakémonos, etc..)
- [ ] Préparation de l'itw
```

**Comment by RodolpheGagetta** [comment]
Prévoir un départ pour Cannes le 4/10/24
