### ISSUE TITLE
Enregistrement des données utilisateurs en transverse

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1090]
Enregistrer les données utilisateurs, à savoir le SIRET et l'effectif sur l'ensemble du site : 
- [ ] Définir comment : url, cookies, session ou local storage ?

Objectif : 
En tant qu'utilisateur, si je réalise l'un des deux parcours, puis que je consulte une fiche projet depuis l'annuaire des projets, mes données entreprise sont prises en compte, de sorte à me montrer uniquement les dispositifs éligibles pour mon entreprise; 

Critères d'acceptabilités :
- [ ] Je ne sais pas par où commencer > Je renseigner mon entreprise > Je renseigne mon nombre de salariés > Je répond à toutes ou une partie des questions > Je vais sur l'annuaire des aides/projets > Je vois toutes les aides/projets

---

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1103
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1104
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1110
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1108
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1216
```

**Comment by dolemoine** [comment]
Hello @ColineLebaratoux,

Mes retours sur tes points: 

* une fois "identifié" (siret et effectif renseigné dans la modale), si l'utilisateur clique sur "je me lance", on saute l'étape "mon entreprise" (question siret + question effectif) pour aller directement au questions thématiques des 2 parcours
:heavy_check_mark:  *je pense effectivement que c'est logique, je trouverais ça pénible en tant qu'utilisateur de devoir à nouveau renseigner des informations déjà communiquées*

* si l'utilisateur clique sur "je me lance" sans avoir été "identifié" au préalable, il complète son SIRET et son effectif dans le parcours classique. Dès lors qu'ils sont complétés, ils sont enregistrés dans la modale, le header se met à jour avec le nom de l'entreprise. https://github.com/betagouv/mission-transition-ecologique/issues/1173#issue-2559130692
:heavy_check_mark: *RAS*

* si l’utilisateur change ses données entreprise via la modale alors qu'il est est sur une page de résultats d'un de deux parcours, alors les résultats prennent en compte le nouveau profil entreprise
:heavy_check_mark: *c'est logique pour moi*

* si l’utilisateur supprime ses données entreprise via la modale alors qu'il est est sur une page de résultats d'un de deux parcours, alors on lui affiche un message d'erreur avec un CTA pour l'inciter à compléter ses données entreprise.
:heavy_check_mark: *je pense que ce point mérite un échange collectif. On pourrait aussi imaginer une alerte indiquant à l'utilsateur qu'il doit refaire un parcours/renseigner ses infos*

:question: d'une manière générale, quelle doit être la logique de suppression des données ? à quel moment les données sont automatiquement supprimées ? Comment on gère le cas où un utilisateur a renseigné ses infos, retourne sur un parcours et se rend compte qu'il doit supprimer ses données s'il veut faire le parcours pour une autre entreprise ?

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat est-ce que vous souhaitez gérer les points de Coline ci-dessus dans des tickets distincts ? https://github.com/betagouv/mission-transition-ecologique/issues/1090#issuecomment-2388823210

sachant qu'au moins un dépends du travail sur la modale, ça me parait judicieux. dans ce cas je propose de valider la première étape correspondant à la description globale de ce ticket

@yvalentin PTI

**Comment by ColineLebaratoux** [comment]
ok @dolemoine je déplace ces points sur un autre ticket 👍

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat, après échanges avec @yvalentin, on préfère extraire l'aspect "filtrage des résultats sur une fiche projet" de cette tâche, pour se concentrer uniquement sur l'aspect enregistrement des datas. Ça parait problématique de filtrer un résultat, sans avertir l'utilisateur et sans lui donner la possibilité de supprimer les informations enregistrer. Cette partie pourra être faite une fois la modale disponible.
Il reste quelques corrections sur l'enregistrement des données, mais cette partie est fonctionnelle.

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat l'enregistrement des données a été merge dans la branche de demo :
https://tee-preprod-pr1228.osc-fr1.scalingo.io/
