### ISSUE TITLE
Décliner et faire évoluer la topbar avec l'éligibilité partielle 🟡 ou non-éligible 🔴

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1103]
En tant qu'utillisateur, j'identifie mon entreprise une fois sur la fiche dispositif. après avoir renseigné mes données entreprise, je souhaite savoir si l'aide consultée est éligible pour mon entreprise. 

- [ ] bandeau "Votre entreprise remplit les critères pour bénéficier de cette aide" 
![Image](https://github.com/user-attachments/assets/b87546f4-33a2-407d-8722-9ffb7c2edaa7)

- [ ] nouveau bandeau "Votre entreprise semble éligible à cette aide." => pour les dispositifs qui comportent des données d'éligibilité spécifique
- accompagné d'un lien "Vérifier les autres critères à respecter" au clic dessus, scroll to section "critères d'éligibilité"

![Image](https://github.com/user-attachments/assets/1dab171f-d846-47f5-8931-d40f451e3aef)

- [ ] nouveau bandeau "Oups ! Votre entreprise n’est pas éligible à cette aide." accompagné d'un CTA pour retourner vers le catalogue des aides filtré sur les critères d'éligibilité de l'entreprise
![Image](https://github.com/user-attachments/assets/abefe401-b71e-45d6-8de4-391c263bcdaf)

Déclinaisons 📱mobiles : 
- Je propose de créer des variantes pour chaque message afin de le synthétiser sur mobile pour éviter d'avoir un bandeau trop haut. 
![Image](https://github.com/user-attachments/assets/6e8cd859-85f4-40b2-ab75-d57ba27af506)

NB : ces évolutions du bandeau amènent à remplacer le bandeau actuel "topbar" (on supprime les données entreprise et le bouton back)
![Image](https://github.com/user-attachments/assets/d4df5e89-12ff-493e-af38-fb576f24c0d5)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1175
```

**Comment by ColineLebaratoux** [comment]
@celinebagault @jbledevehat que pensez-vous de ces formulations ? (version desktop et version mobile)

@ttdm : 
- est-ce que les conditions d'affichage de ces bandeaux sont ok pour toi ? 
- est-ce que les variantes des textes desktop, mobile sont gérables ?

**Comment by ttdm** [comment]
Salut, oui c'est assez simple à gérer. (note pour le tech qui reprendra le ticket: il suffit de vérifier si le champ "éligibilité spécifique" est vide ou non.)
Et pour les variantes de texte, c'est aussi facile à gérer :)

**Comment by ColineLebaratoux** [comment]
"bonne nouvelle, votre entreprise est éligible à cette aide" => 
**reformulations proposées (à discuter ensemble @mpiac @jbledevehat @RodolpheGagetta ):** 
- "Votre entreprise peut prétendre à cette aide"
- "Votre entreprise remplit les conditions d'éligibilité pour pouvoir postuler à cette aide"
- "Votre entreprise peut postuler à cette aide"
- "Votre entreprise remplit les critères pour bénéficier de cette aide".
- "Votre entreprise est admissible à cette aide"
- "Votre entreprise correspond aux conditions requises pour cette aide."
- "Votre entreprise est en droit de demander cette aide."

**Comment by jbledevehat** [comment]
Partons sur "Votre entreprise remplit les critères pour bénéficier de cette aide"

**Comment by ColineLebaratoux** [comment]
@dolemoine j'ai mis à jour les nouveaux textes sur les maquettes
