### ISSUE TITLE
Créer une modale pour saisir son entreprise et taille

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1105]
En tant qu'utilisateur, j'accepte de saisir quelques données de mon entreprise pour disposer de résultats personnalisés pour ma recherche

Création d'une modale intégrant les deux questions nécessaires à l'identification de l'entreprise : SIRET, effectif

- [x] UX UI de la maquette : [lien vers les maquettes](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7696-423969&t=fv725IosqOpawYmv-1)

illustration desktop : 
![Image](https://github.com/user-attachments/assets/4ea00e83-5536-4d1b-b161-35a45404e27c)

illustration mobile : 
![Image](https://github.com/user-attachments/assets/1b31f770-c754-48df-89d3-669cbac7a97e)

- [x] Version desktop et mobile. [lien vers la maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7706-391505&t=fv725IosqOpawYmv-1)

 comportement similaire à celle du site de [la maison de l'emploi ](https://www.maisonemploi-strasbourg.org/actions/)au clic sur "vous êtes"

[lien vers le prototype](https://www.figma.com/proto/tHgzORFkJYTVspsQgR2kg6/TEE-V5?page-id=4712%3A119315&node-id=5955-208714&node-type=frame&viewport=-2728%2C630%2C0.11&t=QVtiEre6PoSlIA5W-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=5955%3A208714)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1172
```

**Comment by ColineLebaratoux** [comment]
Hello @jbledevehat, 
Je viens de tomber [sur ce site ](https://mesaidespubliques.infogreffe.fr/) qui m'a agacé dans un premier temps, puis inspiré 😅

Tu peux tester le parcours avec l'ajout du SIRET ? Je trouve ça pas mal d'avoir des tags avec les informations de l'entreprise, tous modifiable. 

![Image](https://github.com/user-attachments/assets/23f7f94c-7daf-4a5a-bc9d-2e70a991694a)

ça donnerait ça : au clic sur la croix d'un tag, on arrive sur un menu déroulant pour corriger l'info SIRET. (du coup on peut gérer l'effectif de cette manière)
![Image](https://github.com/user-attachments/assets/1d88b1c3-2bb9-4fcd-a9d2-c7e4ca640211)

**Comment by ColineLebaratoux** [comment]
@ColineLebaratoux, création d'un ticket intermédiaire : 
tag localisation non modiafiable 
tag activité non modifiable 
tag effectif en mode select 

quid de "je complète mes infos manuellement" ?
+ création de prochains ticket pour évolution de la modale
