### ISSUE TITLE
UX UI du header avec le CTA "vous êtes...?" et une fois l'entreprise identifiée l'affichage des données entreprise 

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1108]
### **Besoin :** 
1) En tant qu'utilisateur, j'aimerais pouvoir compléter mes données entreprise à différents endroits de mon parcours sur la plateforme (sans avoir à recommencer mon parcours de 0)
2) En tant qu'utilisateur, j'ai besoin de savoir que mes données entreprises sont bien prises en compte sur l'ensemble du site et pouvoir revenir dessus à tout moment

---
### **Proposition :** 

❓**état utilisateur non identifié**
- [ ] Sur écran type Desktop : Ajout d'un bouton "vous êtes ?" dans le header. Au clic afficher la modale
nb : veiller à utiliser la même hauteur pour le bouton "vous êtes" que le hover sur catalogue (nécessite de diminuer sa hauteur à 40 px)
- [ ] Sur écran mobile : ajout d'un icône dans le header. Au clic afficher la modale
![Image](https://github.com/user-attachments/assets/01b90e9d-2118-4b64-996b-004a79434197)

✅ **état utilisateur identifié**
- [ ] Sur écran type Desktop : Afficher l'icône + le nom de l'entreprise dans le header. Permettre un nb max de caractères (par ex. 18 car.) puis couper le nom de l'entreprise avec "..." 
- [ ] Sur écran mobile : ajout d'un icône dans le header. Au clic afficher la modale
![Image](https://github.com/user-attachments/assets/3e8fece7-b545-43ff-b54c-c8142f0a368a)

![Image](https://github.com/user-attachments/assets/179edfdc-976a-4c80-9e27-c634b3625cd3)
![Image](https://github.com/user-attachments/assets/3b0c3d3f-6495-4175-ba9c-c9fa5248a4e6)

---

- [ ] Supprimer les topbar sur la fiche projet et la fiche dispositif (le header ayant pour objectif de remplacer cette info). voir le ticket sur l'évolution de la topbar #1103 

![Image](https://github.com/user-attachments/assets/9a295370-3c0e-4eb1-9924-1e1fc0aa8f55)
![Image](https://github.com/user-attachments/assets/c76a68cc-a551-4009-b465-7dca8cdae136)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1173
```

**Comment by ColineLebaratoux** [comment]
@yvalentin tu en penses quoi ?
