### ISSUE TITLE
Filtrer les aides/projets dans les catalogues avec les données entreprise stocké

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1110]
- En tant qu'entreprise, une fois que je me suis "identifiée", je souhaite que toutes mes recherches sur le site soient filtrées pour mon entreprise, notamment si je consulte le catalogues des aides et des projets.
- En tant qu'entreprise, j'arrive sur une fiche aide depuis une recherche google, je m'identifie depuis la fiche aide et m'aperçois que je ne suis pas éligible à cette aide. Un CTA "voir mes aides éligibles" m'amène sur le catalogue des aides filtrées pour mon entreprise. 

- En tant qu'opérateur, j'ai besoin de tester le catalogue des aides consécutivement avec différents paramètres pour faire des tests. 

---
- [ ] Ajouter un filtre "entreprise" avec le nom de l'entreprise et le détail des données (secteur, localisation, effectif)dans la colonne des filtres. Ces données sont pré-remplis en fonction des informations enregistrées dans la modale. Ce filtre reste toujours ouvert.

- [ ] Ajout d'un indice avec le nb de filtres actifs sur chaque filtre (pour permettre à l'utilisateur de voir en un coup d'oeil quels filtres sont actifs)

conditions d'affichage : 
- [ ] Le filtre entreprise est actif par défaut lorsque l'entreprise est identifiée (modale complétée)

- [ ] Lorsque le filtre entreprise est actif, supprimer le filtre régionale (qui viendrait en conflit avec la localisation de l'entreprise). Lorsque le filtre entreprise est désactivé par l'utilisateur, le filtre régional est reproposé

- [ ] Le filtre entreprise n'est pas visible lorsque l'entreprise n'est pas identifié.

**filtre actif :** 

![Image](https://github.com/user-attachments/assets/a4c9fcc2-c494-4ba6-a6f3-0e0c3475e7e9)

**filtre déséctionné :** 
![Image](https://github.com/user-attachments/assets/1c81290a-93ff-46e9-ba7d-3763c4e6af54)

**utilisateur non identifié**
![Image](https://github.com/user-attachments/assets/79073568-aa6f-4417-ac7f-6d8672b914b1)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1178
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1191
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1431
```

**Comment by ColineLebaratoux** [comment]
un ticket qui peut être lié [#1191](https://github.com/betagouv/mission-transition-ecologique/issues/1191)

**Comment by dolemoine** [comment]
@ColineLebaratoux voilà le lien pour une première passe fonctionnelle : https://tee-prod-pr1400.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
- [ ] Toujours afficher l'encart entreprise, ne pas à replier dans le menu déroulant (qu'elle soit cochée ou décochée) 
- [ ] Sur desktop, diminuer la taille du texte correspondant aux 3 légendes : secteur, localisation, taille (12 pt[ cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7731-420421&t=BTn3oqF6eoANxiJw-1))
- [ ] laisser une colonne dédiée aux picto et une colonne dédiée au texte, cf capture 
![Capture d’écran 2024-12-16 à 15 38 30](https://github.com/user-attachments/assets/21009b68-0c19-4fa5-9c51-b7aa64518b0f)
- [ ] corriger l'interlignage entre deux paragraphe, cf maquette
<img width="265" alt="Capture d’écran 2024-12-16 à 15 38 12" src="https://github.com/user-attachments/assets/79fe30ca-68fb-4787-b589-2f75d2a030a6" />


- [ ] Lorsque le filtre est décoché, alors appliquer un fond gris + des couleurs gris au typo 
<img width="272" alt="Capture d’écran 2024-12-16 à 15 36 51" src="https://github.com/user-attachments/assets/e099727d-369a-4677-9fb7-7bdf1869a125" />

**Comment by ColineLebaratoux** [comment]
- [ ] Côté fonctionnel, le filtre entreprise ne semble pas fonctionner. Il y a le même nb de résultat avec ou sans filtre entreprise

**Comment by dolemoine** [comment]
@ColineLebaratoux les corrections fonctionnelles et d'UI ont été apportées sur l'app test.
J'ai aussi ajouté un reset du filtre de région lorsqu'on a le filtre donnée d'entreprise actif (ce n'était pas fait)

**Comment by ColineLebaratoux** [comment]
Merci @dolemoine ! 
- [ ] Sur desktop, tu peux diminuer encore plus le texte NOM DE L'ENTREPRISE + 3 bulletpoints 

<img width="207" alt="Capture d’écran 2024-12-17 à 09 26 59" src="https://github.com/user-attachments/assets/1ad48987-8c78-4845-8fc1-a40d58ee3991" />
<img width="360" alt="Capture d’écran 2024-12-17 à 09 29 08" src="https://github.com/user-attachments/assets/4b155377-069c-450d-8c6d-d4012793ef55" />

**Comment by ColineLebaratoux** [comment]
- [ ] Sur la page de résultats du parcours "je ne sais pas par ou commencer". Lorsqu'on désélectionne le filtre de l'entreprise, les résultats ne changent pas. 
A mon avis, c'est le comportement le plus attendu. Est-ce qu'on pourrait supprimer la checkbox ici pour que les résultats soient toujours conditionnés pour l'entreprise ? 
https://tee-prod-pr1400.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=je-ne-sais-pas-par-ou-commencer&siret=89806787100019&effectif=EI&locaux=locataire&mobilite=oui&matieres-premieres=maximum&tri-dechets=non&dechets=oui&gestion-eau=oui&energie=oui&audit=oui&selection-audit=performance-energetique#questionnaire-resultat

**Comment by dolemoine** [comment]
Hello @ColineLebaratoux, corrections dispo sur l'app de test : https://tee-prod-pr1400.osc-fr1.scalingo.io/ , dis-moi si les tailles d'icon et de texte te conviennent.

Pour le cas que tu décris sur le parcours "je ne sais pas par où commencer", j'ai plutôt opté pour une checkbox disable, pour garder la cohérence avec le filtre ailleurs (sinon ça demandait un peu trop de bricolage à mon goût pour ne garder que le nom de l'entreprise). Dis-moi également ce que tu en penses, je peux revenir dessus si besoin.

Si tout est ok pour toi, on pourra merge dès que la partie review tech est terminée

**Comment by ColineLebaratoux** [comment]
Salut Dorian

>  Sur desktop, tu peux diminuer encore plus le texte NOM DE L'ENTREPRISE + 3 bulletpoints (et la taille des pictos également).
J'ai l'impression que ça n'a pas bougé 🧐
Tu peux prendre la même taille de picto/typo que pour le montant de l'aide sur une carte dispotif (cf capture d'écrn plus haut)

> Pour le cas que tu décris sur le parcours "je ne sais pas par où commencer", j'ai plutôt opté pour une checkbox disable, pour garder la cohérence avec le filtre ailleurs (sinon ça demandait un peu trop de bricolage à mon goût pour ne garder que le nom de l'entreprise). Dis-moi également ce que tu en penses, je peux revenir dessus si besoin.

Bonne idée, ok pour moi !

**Comment by dolemoine** [comment]
> Salut Dorian
> > Sur desktop, tu peux diminuer encore plus le texte NOM DE L'ENTREPRISE + 3 bulletpoints (et la taille des pictos également).
> 
> J'ai l'impression que ça n'a pas bougé 🧐
> Tu peux prendre la même taille de picto/typo que pour le montant de l'aide sur une carte dispotif (cf capture d'écrn plus haut)

@ColineLebaratoux je n'avais pas bien compris ta demande... 🤦 

Pour le coup la taille de la typo pour le montant de l'aide n'est pas standard (définie à 0.8rem dans une classe css propre au composant). J'ai plutôt tendance à favoriser des tailles standard dans un soucis d'harmonisation.
Je peux proposer les deux tailles standard suivantes : 
XS (0.75rem)
![Image](https://github.com/user-attachments/assets/17f28634-3ae8-43bb-9f49-1fe689b84312)
ou SM (0.875rem)
![Image](https://github.com/user-attachments/assets/0ed420e3-1bfc-4fd2-8cb6-2432ea7f8253)

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine 
Merci !

- [ ] Tu peux partir sur du XS pour la taille des textes des 3 bulletpoints
- [ ] en adaptant l'interlignage, qui est maintenant trop important par rapport à la taille du texte. Tu peux te référer à la [maquette.](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=8006-4
<img width="250" alt="Capture d’écran 2024-12-20 à 15 27 58" src="https://github.com/user-attachments/assets/d9aa6f90-ba1a-4dc7-9be4-6b914ff332a8" />
48126&t=hAco3ILkEWJxbrXD-1)

- [ ] Tu peux aussi réduire l'espace après le dernier bulletpoint et le bord bas du fond vert cf maquette

En effet, ce sont des petits détaile donc je peux tout de suite valider le ticket

**Comment by dolemoine** [comment]
@ColineLebaratoux modif dispo sur l'app de test.
Pour info, la review tech n'est pas finie, et je vais intégrer les nouveautés nuxt dans ma branche car il y a des modifications que l'on a apportées semaine dernière qui ont un impact conséquent sur la récupération des données sur les catalogues.

**Comment by ColineLebaratoux** [comment]
Parfait ! 
En revanche, je n'arrive pas à comprendre pourquoi le filtre entreprise ne s'affiche pas quand je m'identifie en tant que "DINUM" : https://tee-prod-pr1400.osc-fr1.scalingo.io/aides-entreprise?siret=13002526500013&effectif=ETI
<img width="1435" alt="Capture d’écran 2025-01-06 à 09 20 27" src="https://github.com/user-attachments/assets/d3f573f3-f0f2-4a41-ad0c-f3a9ec7867e3" />

**Comment by dolemoine** [comment]
@ColineLebaratoux je regarde pour le cas de la DINUM

**Comment by dolemoine** [comment]
@ColineLebaratoux le bug concernant la DINUM est liée à la récupération des infos d'entreprise, c'est un bug plus global, traité dans un ticket spécifique : #1488 
j'ai traité ce point sur une autre branche ce matin, en court de merge par Yohann

**Comment by ColineLebaratoux** [comment]
alors je valide ce ticket

**Comment by ColineLebaratoux** [comment]
Oups, je viens de voir que sur mobile, l'affichage n'est pas bon. Peux-tu :

- [ ] ferrer à gauche le nom de l'entreprise 
- [ ] aligner les icônes et les textes
- [ ] augmenter la taille des textes dans les 3 bulletpoints (trop petit version mobile)
- [ ] diminuer l'interlignage entre les 3 bulletpoints 

<img width="337" alt="Image" src="https://github.com/user-attachments/assets/c20bbdac-a597-479d-83cc-143f058b9129" />

**Comment by dolemoine** [comment]
@ColineLebaratoux je l'ai traité sur l'app review suivante : https://tee-preprod-pr1467.osc-fr1.scalingo.io/aides-entreprise

**Comment by ColineLebaratoux** [comment]
Hello @dolemoine ! 

Pour l'affichage sur mobile, ça fonctionne uniquement jusqu'à une largeur d'écran de 575 px. 

![Image](https://github.com/user-attachments/assets/773e98fe-0a2e-4259-88fd-8ff41979a2bc)

De manière générale, avoir une colonne sur la gauche n'est pas optimal pour les petits & moyens écrans. Pourrait-on garder l'affichage des filtres sur la gauche uniquement pour desktop ? 

![Image](https://github.com/user-attachments/assets/bd877199-9fb6-4a53-b69c-068b8552d0bb)

**Comment by dolemoine** [comment]
Hello @ColineLebaratoux , 
Oui on peut modifier ça pour avoir la version mobile des filtres à partir d'une largeur d'écran plus grande qu'actuellement.
Je regarde ça et reviens vers toi quand c'est prêt

**Comment by ColineLebaratoux** [comment]
ça me semble très bien, mais on ne le voit plus sur le catalogue des projets. 
on pourra rediscuter de la question des layout et DSFR

**Comment by dolemoine** [comment]
@ColineLebaratoux oui l'App review que je t'ai fourni n'embarque que le filtre côté aides. La partie projet sera merge après celle-ci.
Si c'est ok pour toi je merge cette partie sur les aides
