### ISSUE TITLE
Affichage du message d'erreur sur les différentes pages du site

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1115]
Si erreur (de type timeout, serveur qui ne répond pas, plateforme tombée...)

- [x] Sur le catalogue des aides, supprimer les filtres gauche
![Image](https://github.com/user-attachments/assets/6bf76427-b893-44c7-a3e0-c73ecbeaa397)
- [ ] catalogue des projets : l'alignement du message d'erreur n'est pas bon
![Image](https://github.com/user-attachments/assets/9e683183-8132-4752-8bc9-5039c89a0332)
- [x] sur la page thématique et la page résultats, la gestion des erreur n'a pas été prise en compte, ajouter un message d'erreur similaire à celui sur le catalogue des aides
![Image](https://github.com/user-attachments/assets/ab7d9b1f-c201-4fdf-bdb7-da96fbe1e5b9)
![Image](https://github.com/user-attachments/assets/126562ac-66f8-4b60-9b9b-6d9c964190d5)
- [x] Pour une erreur sur l'envoi du formulaire, passer le message en rouge (et non orange) + réduire la taille du texte 
![Image](https://github.com/user-attachments/assets/252ce631-acf4-4002-9767-85a7e54c64b7)

maquette :
![Image](https://github.com/user-attachments/assets/690a7fd4-5c9f-40d7-ab5a-d45acb78e351)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1116
```

**Comment by jbledevehat** [comment]
Savons-nous comment reproduire cela ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux je pense pas qu'une preprod soit utile dans ce cas la, je t'ai fais des screenshots, dis moi s'il en manque ou si tu veux une demo en direct 
![Image](https://github.com/user-attachments/assets/6c769ced-3ec5-414f-a5f5-5b267dfb6746)
![Image](https://github.com/user-attachments/assets/52e729d7-28a1-4905-a019-3cae0a3e341e)
![Image](https://github.com/user-attachments/assets/34046a10-a91b-49c6-8fae-4841431df2f0)
![Image](https://github.com/user-attachments/assets/c6997de9-23ab-438d-8590-296b54b82f69)
![Image](https://github.com/user-attachments/assets/11235182-37fc-41f1-aa4d-a576e940e863)
