### ISSUE TITLE
Harmoniser le CTA "compléter mon profil" sur la fiche projet avec le header

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1132]
- [ ] Aligner la carte avec les cartes dispositifs 
- [ ] Modifier le texte pour "Vous voulez uniquement voir les aides éligibles pour votre entreprise ?" (puisque maintenant nous affichons toutes les aides disponibles sur un projet à l'utilisateur) et diminuer la taille (cf maquette)
- [ ] Modifier le CTA pour "Je complète mon profil" + le passer en jaune (**gras**) sur fond bleu

En prod : 
![Image](https://github.com/user-attachments/assets/922eee86-5400-4888-b7db-6b4ae3a81ed6)

Vision cible : 
![Image](https://github.com/user-attachments/assets/d437f49f-4d0e-463f-8d6a-442e67a3d35c)

[maquette ](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7713-397764&t=20RoYIka3ToVEiYI-1)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1169
```
