### ISSUE TITLE
UX UI de la carte CTA "je complète mon profil" sur une fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1133]
[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7713-492666&t=20RoYIka3ToVEiYI-1)

- [ ] ajouter une carte CTA "je complète mon profil" en dessous de la section "conditions d'éligibilité". Reprendre le même composant que celui affiché sur la fiche projet [#1169](https://github.com/betagouv/mission-transition-ecologique/issues/1169) en agrandissant homothétiquement l'image (la carte fait toute la longueur de la page)

![Image](https://github.com/user-attachments/assets/65684722-70a8-4078-bb27-69e0cc212eec)

- [ ] modifier les conditions d'affichage du bloc "contactez un conseiller" => ne doit être affiché que lorsque l'utilisateur est identifié :
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1171
```
