### ISSUE TITLE
Bug d'affichage sur les cartes thématiques du parcours "j'ai un projet en tête"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1148]
- [x] en effectuant le changement d'illustrations pour les thématiques biodiv et eau (#985), il semblerait que les tailles des bandeaux & images aient bougé, cf [écran "mon projet"](https://mission-transition-ecologique.beta.gouv.fr/questionnaire/objectifs?choix-du-parcours=j-ai-un-projet&siret=44474511100021&effectif=ETI_GE#questionnaire)

- [ ] Les 2 images mises à jour dépassent de la carte, [peut être suite au ticket 798 ](https://github.com/betagouv/mission-transition-ecologique/issues/798#issue-2325705994)cf capture 

=> est-ce qu'il s'agit d'une erreur de mon côté sur la taille des illus ?

Merci !
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1147
```

**Comment by ColineLebaratoux** [comment]
![Image](https://github.com/user-attachments/assets/6bace710-e098-46ca-a174-1be90ee55f4a)
![Image](https://github.com/user-attachments/assets/f944f9d6-7549-4fdc-b97a-492e007e511e)
![Image](https://github.com/user-attachments/assets/07a74f5c-54a2-468f-869b-13d62a52374b)

**Comment by ColineLebaratoux** [comment]
nouvel svg pour l'eau ![Image](https://github.com/user-attachments/assets/f944f9d6-7549-4fdc-b97a-492e007e511e)

**Comment by ColineLebaratoux** [comment]
ticket sur la même page #1146

**Comment by oumeimaelisbihani** [comment]
![Image](https://github.com/user-attachments/assets/329af5bf-335c-49fe-8942-75ad2e82fe70)
@ColineLebaratoux pour la partie select thématique ça m'a l'air ok en prod!

**Comment by ColineLebaratoux** [comment]
oui tu as raison, ça semble rétabli 👍
