### ISSUE TITLE
Ajouter le CTA "je complète mon profil" sur une fiche dispositif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1171]
Ajouter un CTA "je complète mon profil" sur la fiche dispositif 

**Pour rappel :** 
Cette carte CTA a pour objectif d'inciter l'utilisateur à s'identifier (SIRET effectif) pour lui permettre d'obtenir des résultats personnalisés pour son entreprise. Il est un rappel du CTA présent dans le header (cf ticket #1108)

**comportement :**

Au clic sur le CTA > ouverture de la modale (https://github.com/betagouv/mission-transition-ecologique/issues/1172)

**conditions d'affichage :** 
- Cette carte CTA s'affiche uniquement lorsque l'utilisateur consulte une fiche dispositif sans avoir été "identifié" (nous ne connaissons pas son SIRET et son effectif). 
NB : Le bloc "contactez un conseiller"ne s'affiche jamais en même temps que cette carte CTA "je complète mon profil" (uniquement quand l'utilisateur est identifié)

---
**TO DO :**

[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7713-492666&t=20RoYIka3ToVEiYI-1)

- [x] ajouter une carte CTA "je complète mon profil" en dessous de la section "conditions d'éligibilité". Reprendre le même composant que celui affiché sur la fiche projet [#1169](https://github.com/betagouv/mission-transition-ecologique/issues/1169) en agrandissant homothétiquement l'image (la carte fait toute la longueur de la page)

![Image](https://github.com/user-attachments/assets/65684722-70a8-4078-bb27-69e0cc212eec)

- [x] modifier les conditions d'affichage du bloc "contactez un conseiller" => ne doit être affiché que lorsque l'utilisateur est identifié :
```[tasklist]
### Tasks
- [x] Ajouter le CTA "compléter mon profil" sur une fiche dispositif
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux pour tester : https://tee-preprod-pr1262.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation , disclaimer : le branchement à la modale n'est pas fait

**Comment by ColineLebaratoux** [comment]
Coucou @oumeimaelisbihani ! 
est-ce que tu pourrais me générer ce lien à nouveau stp ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux le voici : https://tee-preprod-pr1262.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation

**Comment by ColineLebaratoux** [comment]
- [ ] Peux-tu ajouter un interlignage un peu plus grand entre le texte et le CTA ?

![Image](https://github.com/user-attachments/assets/2ad73171-8e72-49a8-b69d-0642da31781f)

- [ ] En version mobile, peux-tu supprimer l'image, pour ferrer tous les contenus sur la gauche ?
![Image](https://github.com/user-attachments/assets/0e68cdda-ab6b-4591-89de-b820fa0f3cb9)


NB : je copie ces ajustements sur le ticket #1169 sur lequel ces modifs sont valables également

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux les changements : https://tee-preprod-pr1262.osc-fr1.scalingo.io/aides-entreprise/accelerateur-decarbonation
