### ISSUE TITLE
Mettre en place la modale pour saisir SIRET & effectif

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1172]
Création d'une modale intégrant les questions nécessaires à l'identification de l'entreprise 

**comportement :** 
- La modale s'affiche au clic sur "Vous êtes" dans le header ou sur les CTA présents sur la fiche dispositif  #1171 et fiche projet #1169 
- Les données (siret - effectif) sont enregistrées et prises en compte uniquement lorsque l'utilsiateur clique sur "enregistrer et fermer". Au clic sur "enregistrer et fermer" la modale se ferme et le header se met à jour avec le nom de l'entreprise (cf ticket #1173)
- L'utilisateur peut refermer la fenêtre en cliquant sur "vous êtes" ou sur la croix (mention erreur au niveau des champs concernés si tout n'est pas complété)
- Sur desktop la modale s'ouvre en dessous du header, sur mobile elle s'ouvre au dessus du header. (comportement similaire à celle du site de [la maison de l'emploi ](https://www.maisonemploi-strasbourg.org/actions/)au clic sur "vous êtes")

---
étape choix du SIRET : 
- [x] remplacement du composant actuel pour un menu déroulant avec les résultats de recherche dans la liste des choix, cf maquette 
Les choix affichés ne présentent que le nome de l'entreprise, le siret et le secteur d'activité.
- [x] Au clic sur un résultat, la deuxième étape s'affiche avec les données du SIRET affichés sous forme de tags
- [x] Une fois le résultat selectionné, la mention "je complète mes informations manuellement" peut disparaitre. 

![Image](https://github.com/user-attachments/assets/aaa0e0ae-710f-482e-9ca6-51c33682e2ea)
![Image](https://github.com/user-attachments/assets/c63e17c8-73ba-4a76-9a79-227030916a1a)
---
étape affichage et ajustement des informations : 
- [x]  Votre SIRET : [nom de lentreprise + n° SIRET] s'affiche sous forme de tag. Au clic sur la croix, on retourne à l'étape de "choix du SIRET"
- [x]  Localisation : [code postal + commune] s'affiche sous forme de tag. 
- Pour la V1, ce tag n'est pas modifiable
- Pour une V2, ce tag sera modifiable sous forme de barre de recherche avec autocomplétion[ cf réf infogreffe](https://mesaidespubliques.infogreffe.fr/simulation) => https://github.com/betagouv/mission-transition-ecologique/issues/1202#issue-2578259909
- [x] Activité : [secteur d'activité + code naf]  s'affiche sous forme de tag. 
- Pour la V1, ce tag n'est pas modifiable
- Pour une V2, ce tag sera modifiable sous forme de barre de recherche avec autocomplétion[ cf réf infogreffe](https://mesaidespubliques.infogreffe.fr/simulation) => https://github.com/betagouv/mission-transition-ecologique/issues/1203#issue-2578259909
- [x] Effectif : Le choix du nb d'employés s'effectue également sous forme de menu déroulant. 

![Image](https://github.com/user-attachments/assets/2191ae6a-51a9-4d93-a88d-8722b40e5efd)
[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7827-400017&t=FTUPd8ANNzn6LB9u-1)

- [x] Les 3 champs localisation, activités et effectifs sont obligatoires. Pour la V1, prévoir uniquement un message d'erreur pour ce champ effectif. 
![Image](https://github.com/user-attachments/assets/80c3e7f1-bf08-4c75-ad9f-48f7ca2412a3)

- une fois "identifié", lorsque l'utilisateur clique sur le nom de son entreprise dans le header, il visualise la vue avec le SIRET complété et l'effectif sélectionné. Il peut revenir sur ses choix s'il le souhaite en modifiant et cliquant à nouveau sur "enregistrer et fermer" (ou sur la croix )

**Parcours "je complète les informations manuellement"**

- [x] Choix de l'activité, de la région puis de l'effectif en 3 étapes via 3 menus déroulants
- [x] la mention "je complète les informations manuellement" se transforme en "je complète les informations avec mon SIRET" pour permettre à l'utilisateur de changer d'avis. 
![Image](https://github.com/user-attachments/assets/f4a936c8-68b4-4de7-bf26-f06c2cf31a4d)

---
illustration desktop : 
![Image](https://github.com/user-attachments/assets/e6615117-9105-4562-b667-a93af56a30c1)

illustration mobile : 
![Image](https://github.com/user-attachments/assets/9aea29a2-2bfa-4bac-87fb-4f5d18338ee9)

- [ ] Version mobile : [maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7860-399131&t=iv4K70HN4DD1U5ZW-1)
![Image](https://github.com/user-attachments/assets/c2430845-b00b-4637-9880-b838d93d5836)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1172
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1202
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1203
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1204
```

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani, 
Suite à une discussion avec @jbledevehat et @ttdm, on va opter pour une autre UI pour la modale. [cf ticket design](https://github.com/betagouv/mission-transition-ecologique/issues/1105#issuecomment-2397026167)

il faut qu'on en discute et que je mette à jour le ticket

**Comment by oumeimaelisbihani** [comment]
ok ! je me mets sur l'autre ticket!

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani j'ai bien avancé sur le ticket. Il me manque les illus et les déclis mobiles. En attendant, n'hésite pas à jeter un oeil et me dire si tu as des questions

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux sur le menu déroulant de l'effectif, est ce que le fond jaune sur la fleche est vraiment nécessaire ? ça demanderait pas mal de css pour faire ça

**Comment by ColineLebaratoux** [comment]
hello @oumeimaelisbihani j'ai ajouté une décli mobile et les illustrations svg ✅

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux voila un lien pour voir une v1 https://tee-preprod-pr1243.osc-fr1.scalingo.io/ de la modale ! pour l'instant l'enregistrement n'est pas branché. 
Du coup voila mes questions/remarques : 
pour le parcours manuel :
- j'ai mis des menus déroulants qui ne correspondent pas à la maquette et donc je me demandais pourquoi sur la maquette les composants pour la localisation et l'activité on a pas le même rendu que pour l'effectif alors que c'est bien décrit comme trois menus déroulants ?
- pour la localisation, il est mentionné la ville, est ce que pour cette première version la région (comme c'est dans le parcours actuel) serait suffisante ? 

pour les deux parcours : 
- est ce que l'image du bas de la modale n'apparait pas sur l'étape où on rentre les détails ?
-pour l'effectif surtout dans la maquette, le message d'erreur s'affiche automatiquement ? 

pour l'enregistrement siret : 
- j'ai du bricoler un peu (c'est pas parfait) parce que le composant menu déroulant n'est pas prévu pour permettre un champ de saisie (y'a pas d'autocomplete dans le dsfr)

**Comment by oumeimaelisbihani** [comment]
Nouvelle version : https://tee-preprod-pr1243.osc-fr1.scalingo.io/ avec enregistrement manuel + par siret fonctionnel !

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr1243.osc-fr1.scalingo.io/ @ColineLebaratoux

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux une question qui ressort des reviews techniques : les boutons du header général restent accessibles quand la modale est ouverte, est ce que c'est ok ? si oui , est ce que au clic sur un de ces boutons on ferme la modale ? si non, est ce qu'on grise le header ?

**Comment by ColineLebaratoux** [comment]
Moi je dirais que les boutons du header restent accessibles quand la modale est ouvert. Au clic sur un des boutons on ferme la modale

**Comment by ColineLebaratoux** [comment]
Mes retours sur mobile :

- [ ] Le scroll sur la modale ne fonctionne pas correctement : 
- il manque "vous êtes ?" + sous-titre. (caché sous le header je crois)
- il manque la croix 
- le header ne doit pas être visible 
- la modale ne devrait pas laisser apparaitre la page derrière

[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7860-399131&t=Kjyhz7R1xFJoC1bm-1) : ![Image](https://github.com/user-attachments/assets/68517291-8458-45ba-8539-93e5352c104d)

- [ ] les marges sont inégales à gauche et à droite 

- [ ] sur mobile, mettre en plus petit la mention "combien êtes-vous dans votre entreprise ?" pour que ça tienne dans le select

- [ ] aligner sur la gauche "je complète les informations avec mon SIRET" => doit tenir sur une ligne
![Image](https://github.com/user-attachments/assets/dfe241bd-e6e1-4170-be11-3ccc5da98936)

**Comment by ColineLebaratoux** [comment]
Sur desktop : 

Je suis pas satisfaite de ma proposition sur l'ecran pour compléter les informations manuellement. Je trouve que la mention ""je complète les informations avec mon SIRET" est trop visible. Pourrais-tu stp faire cet ajustement : 
- [ ] diminuer d'un niveau la taille de la mention "je complète les informations avec mon SIRET" (ainsi que la flèche) et le placer au dessus du titre "quelle est votre entreprise ?"

![Image](https://github.com/user-attachments/assets/47ddbbde-e503-426c-beb0-9a05a8041af4)


sur les champs
- [ ] passer la ligne noire en jaune sous les champs ([cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7801-394109&t=Kjyhz7R1xFJoC1bm-1))
![Image](https://github.com/user-attachments/assets/05d2bfb7-96f5-4192-a41e-09db23f5057b)

- [ ] passer les consignes en gris italique

**Comment by ColineLebaratoux** [comment]
- [ ] j'ai l'impression qu'il y a une regression sur le scroll de la modale (le header disparait pour laisser apparaitre la page arrière)
![Image](https://github.com/user-attachments/assets/2e1bd047-4b6c-422b-86e1-4dfdab400092)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux pour les selects de la taille et de l'activité c'est très compliqué (voir impossible) d'avoir uniquement le texte de consigne plus petit ou en italique sans que ça impacte le reste de la liste. Est ce que comme c'est des composants temporaires, ça peut quand meme le faire ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux avec les autres modifications sauf celles sur les selects https://tee-preprod-pr1243.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux avec les branchements de la feature #1260

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani 
Merci, 
Je crois qu'on ne s'est pas comprise sur le nb de résultats affichés pour la recherche SIRET. Il me semblait qu'on s'était accordées sur 3. 
Or ici, on n'en voit plus qu'un. 
- [ ] Peux tu repartir sur un affichage de 3 résultats ?
<img width="728" alt="Capture d’écran 2024-11-04 à 09 29 11" src="https://github.com/user-attachments/assets/fc05a202-1da5-4bc3-a76d-66febac5895c">
- [ ] Quand il n'y a qu'un résultat, peux-tu adapté la hauteur à une seule case ? 
<img width="753" alt="Capture d’écran 2024-11-04 à 09 29 26" src="https://github.com/user-attachments/assets/9df0fd88-7db7-4aa9-bf60-fd437852c2a0">

---

- [ ] Lorsque la modale est afichée, au clic sur "vous êtes" ou "nom de l'entreprise" pourrait-on avoir le même comportement qu'au clic sur la croix ?

---

- [ ] Lorsque la recherche est en cours, pourrait-on remplacer l'icône loupe sur la barre de recherche siret par un petit loader ? (j'ai l'impression que ce composant existait, je me trompe ?)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux les changements >> https://tee-preprod-pr1243.osc-fr1.scalingo.io/ , pour le loader sur la barre de recherche il n'était pas là de base !

**Comment by ColineLebaratoux** [comment]
merci @oumeimaelisbihani 
- [ ] peux-tu harmoniser les consignes dans les champs en gris italique, et diminuer leur taille ?
![Image](https://github.com/user-attachments/assets/67fc4442-c42e-4c43-bc83-3fd26c5d9b5e)

- [ ] dans le parcours "je complète les informations manuellement", il manque les messages d'erreur lorsque l'on valide sans compléter tous les champs

- [ ] Peux tu remplacer ce texte par "je renseigne mon SIRET" => ça ne passe pas sur une ligne et ça m'agace ![Image](https://github.com/user-attachments/assets/5ee6e3c0-61af-426e-ae5e-8068ecfa9837)


point d'amélioration pointue :
- [ ] pour le laoder est-ce que tu penses pouvoir avoir un trait de la même epaisseur que l'icône search et de la même taille (pour fluidifier la transition entre l'icône search et le loader)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est noté ! juste pour le premier point c'est comme j'ai mis plus haut pour les selects de la taille et de l'activité c'est très compliqué (voir impossible) d'avoir uniquement le texte de consigne plus petit ou en italique sans que ça impacte le reste de la liste. Est ce que comme c'est des composants temporaires, ça peut quand meme le faire ?

**Comment by ColineLebaratoux** [comment]
Dac, du coup tu pourras le faire en V2 ? 
Diminuer la taille du texte sur le composant de localisation est possible ?

**Comment by oumeimaelisbihani** [comment]
Oui pour la localisation c'est fait (avec le reste des modifs) c'est ici >> https://tee-preprod-pr1243.osc-fr1.scalingo.io/ @ColineLebaratoux

**Comment by ColineLebaratoux** [comment]
- [ ] Je suis désolée de revenir une nouvelle fois avec une modif sur les intitulés 🙈 mais j'ai l'impression que maintenant la consigne est trop peu lisible dans le select. Je te propose de ne pas diminuer la taille mais de modifier les intitulés des consignes : 
"Quelle est votre région ? " (intitulé qu'on fera évoluer pour "Quelle est votre commune ?")
"Quel est votre secteur d'activité ? "
Sur desktop ""Combien êtes-vous dans votre entreprise ? ", sur mobile "Combien êtes-vous ? "
<img width="633" alt="Capture d’écran 2024-11-05 à 15 07 25" src="https://github.com/user-attachments/assets/826d30ee-46f2-493f-b638-02f4922fd22b">
[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7829-402269&t=NUG8Of41F2cFFoDF-1)

- [ ] ESt-ce qu'il est possible de passer le fond du composant barre de recherche en blanc ? (ça permet d'améliorer le contraste avec le texte, et donc la lisibilité)
<img width="545" alt="Capture d’écran 2024-11-05 à 15 03 25" src="https://github.com/user-attachments/assets/03d19098-c7d7-47ee-af7b-37f27a329f3f">

- [ ] JB a fait la remarque que la croix du tag est peu visible. Peux-tu ajouter systématiquement un espacement entre le texte et la croix pour bien distinguer les 2 ? => La croix doit être accollée au bord droit du tag
<img width="472" alt="Capture d’écran 2024-11-05 à 11 51 28" src="https://github.com/user-attachments/assets/3dc85c57-5352-4141-9e31-226b6247fa81">

**Comment by ColineLebaratoux** [comment]
Coucou @oumeimaelisbihani 

- [ ] Pourrais-tu aligner cette mention avec les autres résultats stp ?
- [ ] Remplacer "cliquez ici" par "[trouver mon SIRET](https://annuaire-entreprises.data.gouv.fr/)"

![Image](https://github.com/user-attachments/assets/cc286334-3be5-4014-bb67-8eaba6481423)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1243.osc-fr1.scalingo.io/ toutes les modifs ! + sélection automatique de l'effectif si entrepreneur individuel

**Comment by ColineLebaratoux** [comment]
Super @oumeimaelisbihani Merci ! 
Une petite coquille à corriger :
<img width="437" alt="Capture d’écran 2024-11-06 à 15 13 19" src="https://github.com/user-attachments/assets/69ac921b-17f8-4e62-8049-3b2b81fc9b31">

On aura surement d'autres modifs suite aux tests de léquipe (cf conv mattermost), courage !

**Comment by oumeimaelisbihani** [comment]
yes c'est changé ici @ColineLebaratoux  >> https://tee-preprod-pr1243.osc-fr1.scalingo.io/ ! est ce que par contre il ne faudrait pas s'accorder sur une version histoire de pouvoir merger sur la branche release et faire un deuxieme ticket avec les modifications ?

**Comment by ColineLebaratoux** [comment]
Pour pallier encore mieux à ce problème :
> JB a fait la remarque que la croix du tag est peu visible. 

- [ ] Peux-tu ajouter un hover sur la croix (le cercle du hover doit être placé de sorte à ce que les espacements avec le bord du tag haut-bas et droit soit identiques)
![Image](https://github.com/user-attachments/assets/e650ce42-6dde-4ef3-ba3a-98f4cc550a55)

- [ ] Est-ce que le curseur main pourrait se mettre automatiquement au survol ?

- [ ] idem pour la croix "quit" en haut à droite, peux-tu ajouter un hover ?
