### ISSUE TITLE
Afficher le CTA "vous êtes...?" + les données de l'entreprise dans le header

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1173]
### **Besoin :** 
1) En tant qu'utilisateur, j'aimerais pouvoir compléter mes données entreprise à différents endroits de mon parcours sur la plateforme (sans avoir à recommencer mon parcours de 0)
2) En tant qu'utilisateur, j'ai besoin de savoir que mes données entreprises sont bien prises en compte sur l'ensemble du site et pouvoir revenir dessus à tout moment

---
### **Proposition :** 

❓**état utilisateur non identifié**
- [x] Sur écran type Desktop : Ajout d'un bouton "vous êtes ?" dans le header. Au clic afficher la modale
nb : veiller à utiliser la même hauteur pour le bouton "vous êtes" que le hover sur catalogue (nécessite de diminuer sa hauteur à 40 px)
- [x] Sur écran mobile : ajout d'un icône dans le header. Au clic afficher la modale
![Image](https://github.com/user-attachments/assets/01b90e9d-2118-4b64-996b-004a79434197)

✅ **état utilisateur identifié**
- [x] Sur écran type Desktop : Afficher l'icône + le nom de l'entreprise dans le header. Permettre un nb max de caractères (par ex. 18 car.) puis couper le nom de l'entreprise avec "..." 
- [x] Sur écran mobile : ajout d'un icône dans le header. Au clic afficher la modale
![Image](https://github.com/user-attachments/assets/3e8fece7-b545-43ff-b54c-c8142f0a368a)

![Image](https://github.com/user-attachments/assets/179edfdc-976a-4c80-9e27-c634b3625cd3)
![Image](https://github.com/user-attachments/assets/3b0c3d3f-6495-4175-ba9c-c9fa5248a4e6)

---

- [x] Supprimer les topbar sur la fiche projet et la fiche dispositif (le header ayant pour objectif de remplacer cette info). voir le ticket sur l'évolution de la topbar #1103 

![Image](https://github.com/user-attachments/assets/9a295370-3c0e-4eb1-9924-1e1fc0aa8f55)
![Image](https://github.com/user-attachments/assets/c76a68cc-a551-4009-b465-7dca8cdae136)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1173
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1090
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1216
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1219.osc-fr1.scalingo.io/ pour tester ! pour l'instant le click sur le bouton change juste l'état du bouton (identifié ou non)

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani 
Merci ! 
- [ ] Est-ce que tu pourrais unifier l'espacement entre les 3 entrées 
<img width="757" alt="Capture d’écran 2024-10-15 à 14 29 29" src="https://github.com/user-attachments/assets/22768132-dbd7-4346-b086-47f0c1feac1c">

- [ ] Afficher plus de caractères pour le nom de l'entreprise (je proposais de couper à 18 car. par ex)

- [ ] ajouter des petites marges autour du point d'interrogation
<img width="382" alt="Capture d’écran 2024-10-15 à 14 32 49" src="https://github.com/user-attachments/assets/6b0a4e47-0532-47c1-aaac-fefcc2f5c9fe">

**Comment by ColineLebaratoux** [comment]
Pour info @oumeimaelisbihani, j'ai lié ce ticket au ticket [#1216](https://github.com/betagouv/mission-transition-ecologique/issues/1216)
