### ISSUE TITLE
UX UI affichage d'une topbar pour indiquer l'éligibilité : vérifiée, partielle, ou non-éligible

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1175]
En tant qu'utillisateur, j'identifie mon entreprise une fois sur la fiche dispositif. après avoir renseigné mes données entreprise, je souhaite savoir si l'aide consultée est élligible pour mon entreprise. 

- [ ] bandeau "Bonne nouvelle, votre entreprise est éligible à cette aide !" 
![Image](https://github.com/user-attachments/assets/9fd73f07-347c-48ec-9a72-36d7f89525b1)

- [ ] nouveau bandeau "Votre entreprise semble éligible à cette aide." => pour les dispositifs qui comportent des données d'éligibilité spécifique
- accompagné d'un lien "Vérifier les autres critères à respecter" au clic dessus, scroll to section "critères d'éligibilité"

![Image](https://github.com/user-attachments/assets/1dab171f-d846-47f5-8931-d40f451e3aef)

- [ ] nouveau bandeau "Oups ! Votre entreprise n’est pas éligible à cette aide." accompagné d'un CTA pour retourner vers le catalogue des aides filtré sur les critères d'éligibilité de l'entreprise
![Image](https://github.com/user-attachments/assets/abefe401-b71e-45d6-8de4-391c263bcdaf)

Déclinaisons 📱mobiles : 
- Je propose de créer des variantes pour chaque message afin de le synthétiser sur mobile pour éviter d'avoir un bandeau trop haut. 
![Image](https://github.com/user-attachments/assets/77218645-e87b-468e-bd26-2bcd8b84e48d)

NB : ces évolutions du bandeau amènent à remplacer le bandeau actuel "topbar" (on supprime les données entreprise et le bouton back)
![Image](https://github.com/user-attachments/assets/d4df5e89-12ff-493e-af38-fb576f24c0d5)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1103
```
