### ISSUE TITLE
[XP Cannes] - Participer au COPIL de l'ARBE PACA

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#1182]
```[tasklist]
### Tasks
- [ ] Présenter les projets/dispositifs biodiversité
- [ ] Discuter sur nationalisation EEN
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1181
```
