### ISSUE TITLE
Passage à la techno Nuxt

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#1186]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1100
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1224
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1072
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1022
- [x] Project Detail via Backend (après merge de cross-siret) / permet de fix le routing autour des pages projets
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/722
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/351
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/323
```
