### ISSUE TITLE
[Release] - enregistrement transverse du SIRET

### ISSUE THREAD

**Issue by dolemoine** [betagouv/mission-transition-ecologique#1301]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/323
```

**Comment by dolemoine** [comment]
@ColineLebaratoux @jbledevehat vous pouvez faire une passe de tests fonctionnels sur cette branche : https://dashboard.scalingo.com/apps/osc-fr1/tee-preprod-pr1276

**Comment by jrayneau** [comment]
@dolemoine j'ai eu l'erreur suivante  "pour votre enterprise.structureSize.undefined du secteur" sur la page de résultat d'action du parcours je ne sais pas par où commencer. (cf screenshot)
J'avais au préalable rempli le "Vous êtes..." avec le nom de ma société Julien Rayneau Consulting
<img width="1276" alt="Capture d’écran 2024-11-15 à 15 55 32" src="https://github.com/user-attachments/assets/832cdac3-753b-42e4-9bf2-f2ffc7b5ea73">

**Comment by jbledevehat** [comment]
Idem sur la page dispositif, entrant par le catalogue des aides, j'en choisi un, "Je complète mon profil" et le formulaire me demande de saisir mon SIRET

**Comment by dolemoine** [comment]
@jrayneau @jbledevehat vos points ci-dessus sont corrigés sur l'app preprod : https://tee-preprod-pr1276.osc-fr1.scalingo.io/

**Comment by dolemoine** [comment]
@ColineLebaratoux oui tout à fait, j'ai traité ça dans une branche qui est en review il me semble, je n'ai pas du la merge dans l'app de preprod... je m'en occupe

**Comment by yvalentin** [comment]
- Régression sue l'input du siret dans le parcours
![Image](https://github.com/user-attachments/assets/936f481b-5ef0-44b9-a8a3-4f6017dc62f4)

⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ 
- Manque la mise à jour de l'url lors de la suppression/modification dans la modale siret
- Quand on est en cours de parcours - manque le retour au début du parcours si suppression de ces infos siret depuis la modale
- 
⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠ ⚠

**Comment by ColineLebaratoux** [comment]
j'ai ajouté ce ticket également : https://github.com/betagouv/mission-transition-ecologique/issues/1327

**Comment by dolemoine** [comment]
- renvoyer une requête quand on se trouve sur la page de choix de la thématique lorsqu'on modifie ses informations d'entreprise

**Comment by dolemoine** [comment]
* [ ] Manque la mise à jour de l'url lors de la suppression/modification dans la modale siret
* [ ] Quand on est en cours de parcours - manque le retour au début du parcours si suppression de ces infos siret depuis la modale
* [ ] Régression input siret parcours
* [ ] Amélioration impact SIRET sur parcours "je ne sais pas par où commencer" #1327 
* [ ] Corriger breadcrumb sur la fiche dispositif d'un projet dans les parcours
* [ ] renvoyer requête page choix thématique à la modification info entreprise
* [ ] setter le usedTrack lorsqu'on renseigne ses infos via la modale avant un parcours
* [ ] corriger la requête avec données qui part même lorsqu'on supprime les données via la modale
* [ ] remettre le bouton retour dans la barre d'éligibilité

**Comment by dolemoine** [comment]
recherche siret en erreur
https://github.com/user-attachments/assets/bf82b698-72b6-4588-afd3-8c3578543b5d

**Comment by dolemoine** [comment]
@ColineLebaratoux pour ton point #1327 je propose de passer automatiquement les étapes si on est sur un parcours -> champ SIRET et qu'on rempli les infos via la modal -> redirection sur choix thématique (parcours j'ai un projet) ou question thématique construction (parcours je ne sais pas par où commencer). Il faudra quand même se poser la question du comportement attendu si en cours de parcours je retourne sur la recherche SIRET via le menu latéral (point non traité pour le moment)
c'est testable ici : https://tee-preprod-pr1338.osc-fr1.scalingo.io/

Le reste des points ne me semble pas bloquants pour un passage en prod. (@yvalentin PTI)
