### ISSUE TITLE
évolution modale : remonter les contenus au dessus de la ligne de flottaison

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1328]
Le bouton ""sauvegarder et quitter" est situé sous la ligne de flottaison, il y a peut-être un risque que l'utilisateur passe à côté de la validation et qu'on ne prenne pas en compte ses données.

![Image](https://github.com/user-attachments/assets/9b00dcb3-0f6c-4411-9ed6-c5977c8dd8ee)

cible : 
![Image](https://github.com/user-attachments/assets/68a1922c-b883-4434-850c-e3dcd85ed420)
[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7827-400017&t=IDiXjnmWFaoxEMEp-1)

to do : 

- [x] diminuer la taille du titre "vous êtes" cf maquette
- [x] mettre le sous titre sur une seule ligne (sur desktop)
- [x] passer le nom de l'entreprise et le siret sur une seule ligne (uniquement sur desktop. Sur mobile conserver la cesure entre le nom et le siret)
- [x] revoir les espacements entre le sous titre et les tags, entre les tags et le CTA (voir les espacements sur la maquette)
=> objectif : le CTA "enregistrer et quitter" visible au premier coup d'oeil
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1435
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux un premier essai, le sauvegarder est visible au dessus de la ligne de flottaison pour un écran min 640px https://tee-preprod-pr1366.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Je suis passé à côté de ton message @oumeimaelisbihani  
@ttdm @yvalentin ou @dolemoine est-ce que vous pourriez me regénerer le lien de preprod ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux le voila : https://tee-preprod-pr1366.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani ! 
je veux bien un nouveau lien stp 🙂

**Comment by ColineLebaratoux** [comment]
merci !
