### ISSUE TITLE
Mettre à jour la promesse sur le bandeau principal de la HP

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1371]
Objectif : 
- clarifier dès le premier coup d'oeil la promesse pour l'utilisateur, à savoir :  
  - spécialisée en **TE** 
  - à destination des entreprises et plus particulièrement des **TPE PME**
  - plateforme **publique** qui centralise uniquement les aides publiques= confiance / service **gratuit**
  - une aide qui s'étend de la recherche à la mise en relation (conseil)

---
### **Nouvelle Promesse :** 

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/c7c4bb8e-0ab1-4e30-b2f1-22c616de5012" />

> TPE, PME
> ### **Trouvez les solutions pour la transition écologique de votre entreprise**
> Identifiez facilement les aides publiques adaptées à votre entreprise
 pour concrétiser vos projets de transition écologique.

CTA 
> Je trouve les aides pour mon projet

Consigne UI : 
Bien respecter les sauts de lignes comme sur la maquette sur le titre et le sous-titre en largeur max d'écran 

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/717
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1372
```

**Comment by jrayneau** [comment]
Proposition 2 bis :
TPE, PME,
Trouvez les aides publiques adaptées à votre entreprise pour concrétiser vos projets de transition écologique.
Mais avec un bouton "Rechercher les aides"

**Comment by jrayneau** [comment]
Alternative pour le texte de la proposition 2 :
TPE, PME,
Trouvez les aides publiques pour votre entreprise et concrétiser vos projets de transition écologique.

**Comment by ColineLebaratoux** [comment]
--
Historique des propositions
### **proposition 0 (ancienne) :** 
> TPE, PME
> Trouvez comment allier écologie avec économies

✅ Accroche concise, à l'allure de slogan 
❌ Accroche énigmatique qui ne permet pas de comprendre la promesse du site en un coup d'oeil


---
### **proposition 1 :** 
> TPE, PME
> Bienvenue sur la plateforme publique dédiée à la transition écologique des entreprises

✅ Simple, rassurante, facile à comprendre
⚠️ entre en concurrence avec Agir ? 
⚠️ promesse trop large ?
⚠️ nécessite d'être accompagné d'un CTA avec une action claire de type 'trouvez les aides pour mon projet"
❌ manque la notion d'aide

![Image](https://github.com/user-attachments/assets/503e3b96-c0ea-43ee-9b5f-bfbdb3fb8b10)


--
### **proposition 2 :** 
> TPE, PME, 
> Trouvez les aides publiques adaptées à votre entreprise pour concrétiser vos projets de transition écologique.
✅ notion d'aides (accroche l'intérêt des entreprises)
✅ "adaptées" pour la notion de personnalisation de la recherche
✅ notion de projet concret
⚠️ plus longue et moins facile à lire que la première
![Image](https://github.com/user-attachments/assets/5108db45-ab2d-4703-bcdc-99c94cbea574)


### **proposition 3 :** 
> Le service public qui aide les petites et moyennes entreprises à engager leur transition écologique.

❌ manque la notion d'aide

--
### **proposition 4 :** 
> Le service public destiné aux petites et moyennes entreprises pour favoriser leur transition écologique.

❌ manque la notion d'aide

--
### **proposition 5 :** 
> TPE, PME
>  Bienvenue sur votre boussole des aides publiques à la transition écologique de votre entreprise.

✅ Le mot boussole suggère un accompagnement, le rôle de guide dans un environnement potentiellement complexe, en aidant les entreprises à trouver leur chemin parmi une multitude de dispositifs d’aides.

---
### **proposition 6 :** 
"TPE, PME
"Des solutions pour la transition écologique de mon entreprise" 
CTA "trouvez les aides pour mon projet"

selon mon secteur 
selon ma taille 
selon ma zone géographique

cf j'agis
![Image](https://github.com/user-attachments/assets/b542847d-46dd-4f5a-a683-37902ec98520)


```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/717
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1372
```

**Comment by ColineLebaratoux** [comment]
@jbledevehat dernière modif proposée pour la formulation de la promesse : 

![Image](https://github.com/user-attachments/assets/284f776c-7a80-4e35-89ec-1373b8367815)


ok pour toi ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux à tester : https://tee-preprod-pr1585.osc-fr1.scalingo.io/

**Comment by jbledevehat** [comment]
Pour moi c'est bon

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani ! 
En largeur max, est-ce que tu pourrais faire les retours à la ligne comme sur la maquette ?

<img width="382" alt="Image" src="https://github.com/user-attachments/assets/69a32582-99f2-42cf-a3dc-a27b946f376e" />

☝️ On a un sujet la dessus, il faudra qu'on prenne le temps d'en discuter à l'oaccasion

**Comment by ColineLebaratoux** [comment]
Je valide le ticket, c'est pas necessaire de faire une nouvelle review de mon côté avec cette modif

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est parti en review tech avec les modifs : https://tee-preprod-pr1585.osc-fr1.scalingo.io/ je vais faire plus gaffe là dessus en effet 😓

**Comment by ColineLebaratoux** [comment]
Non mais on a jamais pris le temps d'en parler 😉 Je te partagerai les règles à avoir en tête pour que tu puisses les appliquer sur chaque ticket front.

**Comment by ColineLebaratoux** [comment]
Sur mobile, en revanche, il faudrait que ça reste sur une même ligne, sinon le rendu du titre est un peu cassé 🙃
<img width="403" alt="Image" src="https://github.com/user-attachments/assets/ff9b6137-ca45-4e97-9217-135b80562c68" />

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux ah zut ! c'est modifié : https://tee-preprod-pr1585.osc-fr1.scalingo.io/
