### ISSUE TITLE
Remplacer le corps de la HP par la liste des projets 

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1373]
Refonte du corp de la HP avec le catalogue des projets 

- [x] supprimer les 2 bandeaux : "1, 2, 3" et les contenus thématiques 
![Image](https://github.com/user-attachments/assets/62dc8095-8c29-4612-909c-49c2306a773b)

- [x] Intégrer le catalogue des projets sur la HP (catalogue + navigation avec les tags thématiques + bandeaux thématiques)

- [x] afficher uniquement 9 premiers projets. Possibilité de faire en deux temps : 
- V1 tri des projets avec les priorités avec la colonne "Prio" (2235251) du tableau 
- V2 avec une nouvelle colonne repertoriant les projets les plus demandés issue de l'analyse statistique [#1430](https://github.com/betagouv/mission-transition-ecologique/issues/1430)

- [x] Au clic sur un tag thématique, on reste sur la HP, toujours avec un affichage de 9 projets maximum (tri des projets cette fois ci avec les priorités avec la colonne "Prio" (2235251) du tableau
- [x] Au clic sur un projet, ouverture d'une fiche projet (dans le même onglet)
![Image](https://github.com/user-attachments/assets/c7fce7cc-c702-4f49-a327-0ddda2f96c0b)
- [x] Ajouter un bouton "Voir tous les projets" - Permet l'ouverture du catalogue des projets (dans le même onglet)

version intermédiaire de la HP avec les projets :
![Image](https://github.com/user-attachments/assets/a70c4757-b210-40bb-b0d2-f28dbbc3c2d6)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1397
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1430
```

**Comment by ColineLebaratoux** [comment]
Ticket prêt pour relecture @jbledevehat

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux premier essai : https://tee-preprod-pr1470.osc-fr1.scalingo.io/ il manque notamment les ronds jaunes et verts sur les paragraphes de la fin mais je les ai pas trouvé en svg sur figma

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani 
Je te partage les svg des ronds jaunes et verts. 
![TEE-rondjaune](https://github.com/user-attachments/assets/f6f16162-0ae7-4ad0-a571-c3e1a802b61e)
![TEE-rondvert](https://github.com/user-attachments/assets/98ce0f18-cc8d-4fe0-a251-0644208a40ab)

Est-ce que tu pourras me redonner le lien de preprod stp ?

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1474.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
- [ ] Diminuer la taille du texte "Quel est votre projet ?"
- [ ]augmenter l'espace avant  "Quel est votre projet ?" [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=8236-511195&t=1fuz2jsdXyWc7wAH-1)
- [ ] Peux-tu limiter l'affichage à 9 projets ?

> afficher uniquement 9 premiers projets. Possibilité de faire en deux temps :
> V1 tri des projets avec les priorités avec la colonne "Prio" (2235251) du tableau
> V2 avec une nouvelle colonne repertoriant les projets les plus demandés issue de l'analyse statistique https://github.com/betagouv/mission-transition-ecologique/issues/1430

- [ ] Corriger le "t" sans "voir tou**s** les projets"
- [ ] Est-ce possible de ne pas coller le trait souligné du lien "voir tous les projets"
<img width="264" alt="Capture d’écran 2025-01-09 à 16 20 52" src="https://github.com/user-attachments/assets/feba246e-1661-4456-bfeb-a03ee172d7b4" />
cible : 
<img width="241" alt="Capture d’écran 2025-01-09 à 16 18 59" src="https://github.com/user-attachments/assets/cecbfbcb-107f-4d78-8e23-743db8af1dc6" />

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux voila les changements : https://tee-preprod-pr1474.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux version finale ici : https://tee-preprod-pr1474.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux voila la nouvelle version : https://tee-preprod-pr1474.osc-fr1.scalingo.io/ , je sais qu'il y avait un dernier soucis de grille mais je sais plus où il est

**Comment by ColineLebaratoux** [comment]
Coucou @oumeimaelisbihani 
Merci ! Moi non plus je ne vois plus le soucis d'alignement ✅

qq ajustements 
Sur le CTA  "voir tous les projets" :
- [ ] Est-ce que tu peux augmenter la taille du CTA 
<img width="317" alt="Image" src="https://github.com/user-attachments/assets/3ea30a30-e443-4e83-8069-4daa2425758f" />
- [ ] Est-ce que tu peux également augmenter la taille du fond pour le hover
<img width="320" alt="Image" src="https://github.com/user-attachments/assets/ac45798c-4589-4ef0-89d4-e9dc3c96e692" />

Sur le header 
- [ ] Je me dis que ce serait pas mal de rendre le header sticky sur la HP pour mettre en avant le CTA "Vous êtes". Est-ce que tu peux faire cette modif dans le cadre de ce ticket ou tu préfères que j'en crée un autre ?

**Comment by ColineLebaratoux** [comment]
j'ajoute mes retours sur la promesse au dessus du footer sur le ticket dédié #1410

**Comment by oumeimaelisbihani** [comment]
pour tester : https://tee-preprod-pr1474.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
- [ ] Au clic, sur "voir tous les projets" sur la HP, est-ce qu'on peut garder l'onglet thématique actif sur lequel l'utilisateur était sur la HP ?

**Comment by ColineLebaratoux** [comment]
- [ ] est-ce que tu peux unifier la taille des logos (comme ce qui est fait dans le footer ?) <img width="376" alt="Image" src="https://github.com/user-attachments/assets/0e3f62df-1566-432f-8145-7ff5f796bec1" />

- [ ] est-ce que tu peux supprimer tous les logos dans le footer (en doublon maintenant)

<img width="1424" alt="Image" src="https://github.com/user-attachments/assets/c6225f2f-4d8c-474b-a966-55f964cfda8b" />

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux la nouvelle version : https://tee-preprod-pr1474.osc-fr1.scalingo.io/
