### ISSUE TITLE
Refonte UI de l'entrée du parcours "je ne sais pas par où commencer"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1376]
Le parcours "Je ne sais pas par ou commencer" n'est plus accessible via le CTA "je me lance" sur la HP (ticket #1372)

- [ ] Créez une nouvelle entrée pour le parcours  "je ne sais pas par ou commencer" qui sera présente sur la HP et sur la page "catalogue de projets" sous une forme de carte, à insérer après les cartes projets. 
- Sur la HP, elle apparait comme étant la dernière carte (et donc la 9e) des propositions de projets. Elle n'est présente que sur l'onglet "tous"
- Sur le catalogue des projets, elle apparait comme étant la toute dernière carte de la liste "tous". Elle n'est présente que sur l'onglet "tous"
- Cette carte ne doit pas être affichée sur la liste des projets de la page de résultats du parcours "je ne sais pas par où commencer"

- [ ] Au clic sur le CTA "J'identifie mes actions prioritaires", l'utilisateur est dirigé vers le parcours "je ne sais pas par où commencer" (étape SIRET s'il n'est pas identifié / première question thématique s'il est déjà identifié)

[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=8088-91814&t=tq2oEmJUoRKvmTjC-1)

### Texte 
Titre de l'encart : (césure après "pas")

> Vous ne savez pas 
> par où commencer ?

description : 
> En moins de 2 minutes, répondez à quelques questions pour identifier vos **projets prioritaires** et les **financements** disponibles pour votre entreprise.

CTA : 
> "J’identifie mes projets prioritaires"

<img width="703" alt="Image" src="https://github.com/user-attachments/assets/908adcfb-e447-40ba-a5e5-24bf42979e63" />

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1427
```

**Comment by ColineLebaratoux** [comment]
proposition alternative (mise en côté) : 
### **sous forme de bandeau** 
![Image](https://github.com/user-attachments/assets/00c11896-0f3d-4e6f-bbe1-facaf4e2e6a8)
✅ entrée plus visible
✅ plus de place pour le CTA

**Comment by ColineLebaratoux** [comment]
@jbledevehat peux-tu relire cette carte ?

**Comment by ColineLebaratoux** [comment]
merci @dolemoine ! 

- [ ] Concernant l'étape SIRET, je me dis qu'il suffirait peut-être de rempalcer le nom du CTA "enregistrer et fermer" par "suivant"+ icône flèche. Ce changement peut-être facilement appliqué ?

<img width="1111" alt="Image" src="https://github.com/user-attachments/assets/cec668e9-9d5a-4253-a3c9-8ce6fc0f682e" />

- [ ] concernant l'UI de la carte "vous ne savez par par ou commencer". Est-ce possible de caler les retours à la ligne par défaut comme sur la maquette ? + diminuer l'espace entre le CTA et le texte : (à corriger)

En moins de 2 minutes, répondez à quelques questions pour identifier vos projets prioritaires et les financements disponibles pour votre entreprise.

**Comment by ColineLebaratoux** [comment]
ok, on peut réflechir à ça ! 
Et l'idée de remplacer le nom du CTA "enregistrer et fermer" par "suivant" (comme sur les étapes du questionnaire) c'est possible ?

**Comment by dolemoine** [comment]
@ColineLebaratoux oui le remplacement du CTA c'est ok (cette modification est en cours de déploiement sur l'app test)

**Comment by dolemoine** [comment]
@ColineLebaratoux si c'est ok de ton côté, je clean la partie identification dans le questionnaire (supprimer entreprise dans le parcours et dans le bandeau de gauche et éviter les confusions et les erreurs)

**Comment by ColineLebaratoux** [comment]
ok !

**Comment by ColineLebaratoux** [comment]
> On peut aussi adapter le titre dans la modal pour indiquer qu'il s'agit d'un parcours de question (remplacer le texte "Vous êtes...? Renseignez votre profil entreprise pour visualiser les aides éligibles et les projets pertinents pour votre secteur.")

bonne idée ! Je propose : 

<img width="487" alt="Image" src="https://github.com/user-attachments/assets/38653b7f-b61d-4bc5-addc-b72ff0533c71" />

**Comment by dolemoine** [comment]
pour le hover, est-ce que j'utilise une couleur de notre charte ? je suis pas spécialiste, si tu peux jeter un coup d'oeil!

**Comment by dolemoine** [comment]
j'ai utilisé le 30% du blue-france qui semble être #9292ff
je viens de push en utilisant le 30% de la couleur purple, ça me semble pas mal (en cours de déploiement)
sinon tant pis on mettra une couleur custom

**Comment by ColineLebaratoux** [comment]
ok très bien

**Comment by jbledevehat** [comment]
@dolemoine J'ai vu qu'il y avait une variable qui n'était pas ouf en testant. Dans la phrase juste au dessus des 3 cartes. Il serai préférable d'écrire TPE plutôt que MICRO. (ici entreprises de moins de 10 salariés).

<img width="1286" alt="Image" src="https://github.com/user-attachments/assets/315b75a1-ec14-48e4-ab4e-9f4cc3345a2e" />

**Comment by dolemoine** [comment]
@jbledevehat aujourd'hui on fait la distinction MICRO et TPE : 

![Image](https://github.com/user-attachments/assets/241fc652-45b2-4f40-9ffb-f71411ee1478)

est-ce que le terme à utiliser dans les deux cas est TPE ? Ce changement impactera l'ensemble de l'app pour rester cohérent

**Comment by dolemoine** [comment]
@ColineLebaratoux si tu veux refaire une passe fonctionnelle pour validation : https://tee-preprod-pr1653.osc-fr1.scalingo.io/
