### ISSUE TITLE
Sur la page d'accueil, afficher les projets les plus demandés issue de l'analyse statistique

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1430]
- [ ]  Sur la HP uniquement, afficher les 9 projets les plus demandés issus de la nouvelle colonne du ticket #1432 (nouvelle colonne sur baserow pour identifier une liste des projets les plus demandés toutes thématiques confondues.
Pour faire simple, on opte pour une liste statique issue de l'analyse statistique à un temps T. ex :  isolation thermique, éclairage LED, panneaux solaires, véhicules propres,  économies énergie... 
- [ ] Si filtre sur une thématique afficher les 9 projets par prio sans prendre en comptes les mises en avant.

--

NB : en réalité, dans un second temps, il s'agira uniquement des 8 premiers projets puisque qu'on va ajouter une carte "je ne sais pas par ou commencer" à la neuvième place de la liste cf #1376

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1432
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1373
```
