### ISSUE TITLE
Mettre en place un filtre sur la partie catalogue des projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1431]
En tant qu'entreprise, une fois que je me suis "identifiée", je souhaite que toutes mes recherches sur le site soient filtrées pour mon entreprise, notamment si je consulte le catalogues des aides et des projets.

- [ ] Une fois l'entreprise identifiée, filtrer le catalogue des projets avec uniquement les projets pertinents pour son secteur 

Ticket lié côté affichage front 1433

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1433
```

**Comment by dolemoine** [comment]
@ColineLebaratoux app review : https://tee-preprod-pr1467.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@dolemoine ce ticket est en "need validation" = tu aurais le lien de test ? 
J'ai essayé ici https://tee-prod-pr1400.osc-fr1.scalingo.io/projets-entreprise?siret=80387770300030&effectif=EI mais le filtre n'a pas l'air d'être mis en place

**Comment by dolemoine** [comment]
@ColineLebaratoux je te fais signe dès qu'on a résolu les soucis de déploiements

**Comment by dolemoine** [comment]
@ColineLebaratoux ce sera cette app review  : https://tee-preprod-pr1467.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
✅ Le filtrage fonctionne 

❌ qq bugs en revanche : 
- [ ] les icônes sont déformés
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/00ae5034-b5cb-4f23-a31e-a87371d94c45" />
<img width="280" alt="Image" src="https://github.com/user-attachments/assets/6a4886d4-d65c-47ed-bbda-cf13053f80fe" />
<img width="223" alt="Image" src="https://github.com/user-attachments/assets/2922fbd7-2ade-419b-99cc-0eccba51fd13" />

- [ ] Le clic sur le bouton "enregistrer et fermer" sur la modale ne fonctionne pas sur la HP

**Comment by dolemoine** [comment]
@ColineLebaratoux les points au dessus sont traités sur l'app review.
Il reste un soucis sur le spinner, mais il est général à toutes les pages de résultats

**Comment by ColineLebaratoux** [comment]
Coucou @dolemoine ! 
Tu m'as dit lundi que tu me redonnais le lien de test ?

**Comment by dolemoine** [comment]
hello @ColineLebaratoux totalement zappé : https://tee-preprod-pr1467.osc-fr1.scalingo.io/
review tech en court

**Comment by ColineLebaratoux** [comment]
merci !
