### ISSUE TITLE
🌈 Epic :  iframe TEE V1

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#1453]
**Comment s'intégrer sur d'autres sites pour gagner en acquisition ?**
1) AGIR 
2) Portail RSE 
3) Atout France

Plusieurs types de liens possibles : 
- Un lien générique vers la plateforme TEE 
- Un lien vers la fiche projet 
- Un lien vers la plateforme décliné par secteur qui fait le lien vers la landing page secteur

---

TO DO 
- Réaliser une analyse tech pour définir si on met en place un iframe et/ou webcomponent pour s'intégrer sur d'autres sites
[#1509](https://github.com/betagouv/mission-transition-ecologique/issues/1509) @yvalentin 
- Demander à l'équipe projet Agir s'ils préfèrent intégrer un webcomponent ou un iframe ? @jbledevehat 
- Poser un retro-planning avec l'équipe Agir des évolutions à mettre en place 
- Revoir le design du widget TEE #1528 @ColineLebaratoux

**Comment by jbledevehat** [comment]
Ajustements suite à rapide mise en prod : 
- [ ] Revoir la taille de l'image
- [ ] Ajouter le logo MTE
- [ ] Attente des retours AGIR
- [ ] Écrire une note explicative pour nos partenaires 
- [ ] Intégrer un bouton "</> intégrer" dans le projet ? à l'image de par exemple [ImpactCO2](https://impactco2.fr/outils/chauffage)
