### ISSUE TITLE
🌈 Epic : Déploiement sectoriel Tourisme / XP Cannes

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#1455]
### Intro
- [x] Prendre contact auprès du GT sectoriel
- [x] Présenter notre service au GT
    - [x] Intégrer le GT sectoriel à l'ADEME
### Actions
- [x] Lister les actions déjà référencé sur ce secteur (dans les 180, ou autres déjà existantes)
- [x] Animer un atelier de travail avec le GT pour définir les actions
- [x] Avoir une liste de 5 à 10 actions sectorielles avec ses "en savoir +"
    - [x] Écrire les actions
    - [x] Ajouter ou lier les principaux dispositifs **nationaux** aux actions
    - [x] Ajouter ou lier les principaux dispositifs **régionaux** aux actions #1340 
    - [x] Relier les autres secteurs d'activités pertinents sur les nouvelles actions
- [x] Récupérer les coordonnées des OP pour communiquer auprès d'eux (au sein de l'ADEME ou SGPE...) - [Annuaire de contact](https://baserow.io/database/114839/table/397740/707517)
- [x] Publier les actions
- [x] Faire relire les actions au référent et experts concernés et apporter les modification #1675 
### Com
- [x] Prendre contact avec les DR, informant qu'on prendre attache auprès des CR (A SUPPRIMER - non réalisé)
- [x] Contacter les CR qu'on intègre leur aide #1456 (A SUPPRIMER - non réalisé)
- [x] Campagne mails #1540 
     - [x] ADEME auprès des entreprises Tourisme (national)
     - [x] Auprès des OP #1762 
- [x] Webinaire (A SUPPRIMER - non réalisé)
- [x] Com Réseaux sociaux (A SUPPRIMER - non réalisé)
