### ISSUE TITLE
Layout des pages

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#743]
Revoir le layout des pages 
https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6481-213822&t=SZcb9ajAF3C3Tfng-1

### Tasks
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/970
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/974
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/975
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/876
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/906
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/1642
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/1655
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/1673
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/1241
- [x] https://github.com/betagouv/mission-transition-ecologique/issues/1611
