### ISSUE TITLE
Correction UI du message "Aucune aide n'a pu être identifiée ..."

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#748]
Sur la page de résultats des 2 parcours ou l'annuaire, modifier le message lorsqu'il n'y a pas d'aides ou d'actions trouvées

- [x] reformuler "Aucune aide n’a pu être identifiée sur cette thématique..." /  "Aucune idée d’action n’a pu être identifiée sur cette thématique..."
- [ ] diminuer les tailles de l'illustration et du texte (beaucoup trop gros aujourd'hui)
- [ ] changer l'illustration = la même que sur la page statistique 

ne pas mettre dans un premier temps "voir toutes les aides"

---
**Cible**
onglet "vos aides financières" [=> maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7183-358940&t=VvGDSmpTDVJPa9CC-1)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/a67f42e0-5891-4b96-ae1d-725ce394bfbd)

onglet "des idées d'actions à mettre en place" [=> maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7183-329429&t=VvGDSmpTDVJPa9CC-1)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/bea1ae2b-788f-4b2f-b9ef-1b507d89251b)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/874
```

**Comment by oumeimaelisbihani** [comment]
Pour validation https://tee-preprod-pr927.osc-fr1.scalingo.io/ @jbledevehat

**Comment by jbledevehat** [comment]
Nickel
