### ISSUE TITLE
Faire évoluer l'étape "quel est votre objectif prioritaire" sur le parcours "j'ai un projet en tête"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#759]
En tant qu'utilisateur, je souhaite identifier facilement mon projet afin de trouver les aides disponibles pour m'aider à le mettre en place. 

- [ ] Remplacer  "quel est votre objectif prioritaire"+"je souhaite" par "Choisissez la thématique de votre projet"
- [ ] Faire évoluer les select thématiques pour un système de cartes intégrant : 
- l'illustration thématique sur un fond light (10%) cf correspondances ci-dessous : 
https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6254%3A271572&t=3EVrubpJCj4sB8YY-1
- 2 à 3 tags "projets" cliquables dans chaque carte (nécessaire d'identifier dans les données les 2,3 projets exemples)+ état hover DSFR 
- suivi de points de suspension (pour laisser comprendre qu'il y a d'autres projets à découvrir derrière la carte)
Comportement : 
- Au clic sur un tag > direction directement sur la fiche projet correspondante (précédé d'un loader)
- Au clic sur une carte > direction sur la page "vos résultats" (précédé d'un loader)

- [ ] Mettre à jour le fil d'ariane sur le bandeau gauche avec "🎯 mon projet"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/dc3a374a-9d97-4424-b5c4-cc77c686d33e)

hover carte / hover tag : 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/cea7c6e9-1fb3-4252-8c38-3e038072c5ba)

---
version mobile : 
- [ ] Enlever les illustrations
- [ ] appliquer la couleur du fond sur la carte

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/324f0d01-3626-4ec2-b906-7437da2148d5)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/797
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/798
```
