### ISSUE TITLE
Intégrer le fil d'étape (fils d'ariane)

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#761]
- [ ] Intégration du fil d'ariane[ cf documentation DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/fil-d-ariane/)
Notre objectif : faciliter au maximum la navigation avant arrière. entre les projets < > fiches projets < > fiches dispositifs
- Afficher sur toutes les pages sauf les pistes de questions), sur toutes les tailles d'écran
- au clic sur "questionnaire" renvoyer vers la dernière étape du questionnaire
- Sur mobile, afficher "voir le fil d'ariane" (cf bonne pratiques documentation)
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/585f91dd-36a2-4da9-beb3-b86d22f5afd5)

[page de résultats](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6571-369849&t=9Daipd7h6G83gXZQ-1)

[fiche projet](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6799-464423&t=9Daipd7h6G83gXZQ-1)

[fiche dispositif](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6819-411092&t=9Daipd7h6G83gXZQ-1)

ticket lié : [#871](https://github.com/betagouv/mission-transition-ecologique/issues/871)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/871
```

**Comment by ColineLebaratoux** [comment]
A définir.: le fil d'étape remplace t-il le back ? 

- [ ] soit ajouter un bouton back complémentaire
- [ ] soit revoir l'UI du fil d'étape pour le rendre plus visible

**Comment by dolemoine** [comment]
@ColineLebaratoux : si je comprends bien, on souhaite intégrer le fil d'ariane uniquement sur le parcours "j'ai un projet en tête"? Ou est-ce qu'on part du principe qu'il est global et qu'on le veut partout  ?
La doc du composant du DSFR précise que plusieurs éléments sont obligatoires, notamment la page accueil, la page courante, et toutes les étapes entres les deux.
Il va falloir qu'on adapte le composant à notre sauce pour avoir un comportement différent.
Tu peux me ping sur mattermost pour en discuter rapidement

**Comment by ColineLebaratoux** [comment]
@dolemoine il faudrait l'intégrer sur les différents parcours pour être cohérent. Je n'ai pas encore creuser le sujet, il faut que je me penche sur les implications sur chaque page. (Quid du bouton retour, du formulaire, des pages catalogue...)
Je me penche dessus dès que j'ai un peu de temps. Est-ce que tu pourrais passer sur un autre ticket en attendant ?

**Comment by dolemoine** [comment]
@ColineLebaratoux c'est noté, je passe sur une autre issue en attendant.

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr924.osc-fr1.scalingo.io/ pour tester cette issue et la 871 @jbledevehat

**Comment by jbledevehat** [comment]
Après coup je pense que le fils d'Ariane devrait être aligné sur l'en-tête. Car le voir tout à droite sur grand écran c'est pas naturel

![Image](https://github.com/user-attachments/assets/19e88dc9-87bc-425d-adff-fd05cd4678d1)

**Comment by jbledevehat** [comment]
Nickel c'est good
