### ISSUE TITLE
Sur la page de résultats du parcours "jai un projet en tête", ajouter le CTA "j'ai un autre projet"

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#762]
En tant qu'utilisateur, je ne retrouve pas le projet que j'ai en tête.

Objectif : 
- donner une solution de repli à l'utilisateur dont le projet n'est pas référencé sur la plateforme = la possibilité d'expliquer son projet directement à un conseiller

To do : 

- [x] Intégrer un CTA (en largeur des 3 colonnes projets) en bas de la liste des projets "J'ai un autre projet"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/17b5a27a-1672-4214-9b8b-959c4ba3580d)

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/c2b0f905-0de5-45fe-8f20-7a5727865c80)

- [x] Au clic sur le CTA, évolution du CTA en formulaire de contact "👋 Expliquez nous votre projet, nous vous mettons en relation 
avec un conseiller compétent pour votre demande sur votre territoire", intégrant 2 champs complémentaires : 
- "Quel est le nom de votre projet ?" (objectif collecter les noms des projets pour les stats et faire remointer des besoins d'intégration de futurs projets)
- Thématique (la thématique est sélectionnée par défaut en fonction du tag séléctionné en haut de la page) + menu déroulant des 8 thématiques du projet avec les emojis
- Modifier "Quel est votre besoin" par "quel est votre projet"
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/e72f9f8b-c8b5-44f8-a352-e86353ea381e)

- [x] Au clic sur envoyer > message de confirmation "Un conseiller compétent pour votre demande sur votre territoire vous contactera prochainement par mail ou par téléphone pour échanger sur votre projet et répondre à vos questions"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/be21e282-4268-4f5c-bb35-1683cde7e303)

- [x] Lorsqu'il n'y a aucun projet dans la thématique, alors afficher directement le formulaire sous la message "aucune aide..." :
[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=7268-339073&t=h6Zdp2mCasexHUto-1)

![Image](https://github.com/user-attachments/assets/15574e2a-1712-41c8-b98d-3c59a0d08502)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/748
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1066
```

**Comment by yvalentin** [comment]
@jbledevehat @ColineLebaratoux @celinebagault 
Définir quel est la gestion des demandes faites par ce formulaire ?

En gros, qu'est-ce que l'on fait des données saisi par l'utilisateur (envoie sur brevo, pipeline spécifique, envoie sur PDE...) ?

**Comment by jbledevehat** [comment]
@ttdm je t'ai ajouté une tache, que j'ai converti en issu

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani

- je n'ai pas compris ce que tu voulais dire par "est ce qu'il vaudrait pas mieux laisser le bouton qui fait apparaitre le formulaire en bas de liste pour avoir la possibilité de le refaire disparaitre". Tu peux m'en dire plus ?
- à chacun de mes test, j'ai un message d'erreur à la fin. Est-ce que je pourrai tester le parcours jusqu'au bout ?


Mes retours : 
- [ ] corriger le hover du bouton "j'ai un autre projet" pour une couleur plus light 
![Capture d’écran 2024-09-24 à 11 49 31](https://github.com/user-attachments/assets/6253776a-4989-4d57-ad22-668523e6b61e)

- [ ] utiliser le signe + de la maquette figma (bords arondis)
![plus](https://github.com/user-attachments/assets/d3b348e2-7ad9-43da-a65e-16b5ab5e166a)

- [ ] adapter la carte version mobile (mettre sur une ligne / agrandir le picto "+")
**actuel**
![IMG_781656A3C27B-1](https://github.com/user-attachments/assets/498dc0cc-c16d-4444-98a5-270086ebd33a)
[**maquette** ](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6284-324776&t=c0XSEQOvLnn7NB3F-1)
<img width="402" alt="Capture d’écran 2024-09-24 à 11 54 14" src="https://github.com/user-attachments/assets/9eefc2bc-08dc-41cd-91f5-12d6f832e997">

- [ ] Serait-il possible d'ajouter une interaction au clic sur "j'ai un autre projet" pour déployer le formulaire, de ce type : 
https://github.com/user-attachments/assets/27232ec9-fd0c-4e3d-bae3-ebd907b992d3

- [ ] Au clic sur envoyer, il faut faire scroll up sur le message d'erreur/confirmation.

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani, merci. Voilà mes retours : 

- [ ] Sur cette version, on supprime "contactez un conseiller", le sous-titre est plus grand, et passe en gras (cf maquette). L'idéal aussi ce serait de gérer manuellement la césure, de sorte à ce que le texte "avec un conseiller compétent..." démarre en deuxième ligne. 
<img width="1109" alt="Capture d’écran 2024-10-29 à 09 03 44" src="https://github.com/user-attachments/assets/06665317-da97-434c-89ed-8219ef357e1a">
cible : 
<img width="647" alt="Capture d’écran 2024-10-29 à 09 04 40" src="https://github.com/user-attachments/assets/111ffe8c-deba-49d6-9b12-be369020b97f">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux avec les nouveaux changements >> https://tee-preprod-pr1214.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci !
- cool l'animation de transition en fondu 👌
- est-ce que tu peux augmenter d'un niveau le sous-titre (qui devient titre) "expliquez-nous votre projet" 
cf maquette
<img width="644" alt="Capture d’écran 2024-10-30 à 12 21 52" src="https://github.com/user-attachments/assets/1ca35c2e-9cec-4d65-8376-064d5faa2a26">


- ajouter un espacement avant ce titre 
<img width="1042" alt="Capture d’écran 2024-10-30 à 10 14 46" src="https://github.com/user-attachments/assets/1c35e99b-b9f9-4aae-a745-caf14b47f454">

- harmoniser les espacements entre les cartes projets et la carte "j'ai un autre projet"

<img width="192" alt="Capture d’écran 2024-10-30 à 12 23 19" src="https://github.com/user-attachments/assets/7c09c342-ce32-46e8-afaa-f7ae096b5884">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux avec les modifications : https://tee-preprod-pr1214.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux j'ai testé dans le cas "je ne sais pas par ou commencer" avec le tag "tous" on a pas de thématique sélectionnée et sinon on a la thématique sélectionnée : https://tee-preprod-pr1214.osc-fr1.scalingo.io/

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux avec les modifications : https://tee-preprod-pr1214.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Super ! 
Presque terminé, des mini corrections UI : 

- [ ] peux-tu mettre le même espacement entre les cartes projets et le CTA "j'ai un autre projet", que celui entre les cartes projets et le formulaire déployé ?
<img width="753" alt="Capture d’écran 2024-11-04 à 10 52 13" src="https://github.com/user-attachments/assets/4a4cb32e-fb51-45ae-946e-22e417cda2ac">
<img width="529" alt="Capture d’écran 2024-11-04 à 10 52 38" src="https://github.com/user-attachments/assets/e9856732-b8f4-449a-a7b9-55afae6183e3">

- [ ] peux-tu ajouter un espace au dessus et en dessous de "j'ai un projet en tête"
<img width="1081" alt="Capture d’écran 2024-11-04 à 10 55 54" src="https://github.com/user-attachments/assets/43c4f377-e91c-4b3c-806f-c2f82ff28d8c">
<img width="371" alt="Capture d’écran 2024-11-04 à 10 58 17" src="https://github.com/user-attachments/assets/6946a5fb-4478-4604-a3b7-a56cae5acce1">

- [ ] Mettre sur fond violet clair (cf maquette) le fond du CTA et au hover passer en violet plus foncé (celui utilisé actuellement)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux les changements >> https://tee-preprod-pr1214.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
tout parfait !
