### ISSUE TITLE
Créer la page catalogue des projets

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#792]
Objectif du catalogue des projets
> pour le référencement
> pour les partenaires 

Côté utilisateur, on péfère qu'il arrive sur les projets via "j'ai un projet en tête"
on ne l'incite pas à arriver sur ce catalogue (sans avoir renseigné son siret) car il verra l'exhaustivité des projets (et non ceux uniquement pertinents pour son secteur d'activité) et ne pourra pas visualiser les dispositifs pour lesquels il est éligible sur les fiches projets. 

[Maquette du catalogue des projets](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6325%3A347586&t=QfQ2wnTLjozoxiMg-1)
La page catalogue des projets comporte : 
- [x]  un bandeau d'entête 
- [x] les bandeaux et tags thématiques (rôle de filtres)
- [x] les cartes projets
- [x] le bandeau contact (lien vers iframe PDE)
- [x] l'URL est : mission-transition-ecologique.beta.gouv.fr/projets-entreprise/
- [x] Changer le sitemap
- [ ] Le bouton Annuaire et renommé et devient un menu avec 2 catalgoue (Aides/Projets) voir #[786](https://github.com/betagouv/mission-transition-ecologique/issues/786)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/786
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/941
```

**Comment by yvalentin** [comment]
Lien de validation (manque le sitemap et la mise à jour du menu avec dropdown 
https://tee-preprod-pr915.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @yvalentin. Quelle est l'url pour arriver direct sur le catalogue des projets ?

**Comment by ColineLebaratoux** [comment]
J'ai un retour : 
- [ ] A l'affichage d'une fiche projet depuis le catalogue des projets, lorsque l'utilisateur clique sur "je complète mon profil" il doit être redirigé vers l'étape SIRET du parcours "j'ai un projet en tête" (et non l'étape de choix)

Autre chose, pour mettre en prod la page catalogue des projets, il est nécessaire que le fil d'ariane soit intégré pour permettre à l'utilisateur de naviguer (hors back du navigateur)

**Comment by yvalentin** [comment]
Il reste normalement le menu pour la catalogue à faire

**Comment by jbledevehat** [comment]
Comment sont trier les résultats ? Je pense que s'il n'y a pas de règle, par priorité serait le bon choix à faire.

**Comment by dolemoine** [comment]
@jbledevehat, un tri est déjà en place pour afficher la liste des projets, basé effectivement sur l'ordre de priorité.

Est-ce qu'il reste de choses à valider sur cette tâche ?
