### ISSUE TITLE
Intérgation des projets via api baserow dans le back

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#796]
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/803
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/804
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/805
```
