### ISSUE TITLE
Evolution graphique des questions des objectives en cards

### ISSUE THREAD

**Issue by yvalentin** [betagouv/mission-transition-ecologique#797]
En tant qu'utilisateur, je souhaite identifier facilement mon projet afin de trouver les aides disponibles pour m'aider à le mettre en place. 

- [ ] Remplacer  "quel est votre objectif prioritaire"+"je souhaite" par "Choisissez la thématique de votre projet"
- [ ] Faire évoluer les select thématiques pour un système de cartes intégrant : 
- l'illustration thématique sur un fond light (10%) cf correspondances ci-dessous : 
https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6254%3A271572&t=3EVrubpJCj4sB8YY-1

- 2 à 3 tags "projets" cliquables dans chaque carte (nécessaire d'identifier dans les données les 2,3 projets exemples)+ état hover DSFR 
(possiblité de mettre les tags en dur dans un premiers temps)
- suivi de points de suspension (pour laisser comprendre qu'il y a d'autres projets à découvrir derrière la carte)
Comportement : 
- Au clic sur un tag > direction directement sur la fiche projet correspondante (précédé d'un loader)
- Au clic sur une carte > direction sur la page "vos résultats" (précédé d'un loader)

- [ ] Mettre à jour le fil d'ariane sur le bandeau gauche avec "🎯 mon projet"

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/dc3a374a-9d97-4424-b5c4-cc77c686d33e)

hover carte / hover tag : 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/cea7c6e9-1fb3-4252-8c38-3e038072c5ba)

---
version mobile : 
- [ ] Enlever les illustrations
- [ ] appliquer la couleur du fond sur la carte

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/324f0d01-3626-4ec2-b906-7437da2148d5)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/797
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/798
```

**Comment by oumeimaelisbihani** [comment]
@jbledevehat @ColineLebaratoux version de test ici >> https://tee-preprod-pr856.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Mes retours pour @yvalentin 

- [ ] Aligner "Choisissez la thématique de votre projet" sur la gauche 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/ed81518d-51d9-46e2-a5a9-ab9cf5032a88)

- [ ] Sur les cartes thématiques, aligner les tags d'exemple de projets
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/cc76317a-22ad-4b59-8785-126c03cff1ec)

- [ ] Sur les cartes thématiques, diminuer la taille du traits de couleur 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/a4a5f822-b1bb-4a17-9eba-bf56ec93e500)

cible : 
![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/5c7cb034-5e8f-4b7e-b45f-54759f8bef1d)

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr856.osc-fr1.scalingo.io/ nouvelle version de test

**Comment by ColineLebaratoux** [comment]
Hello @oumeimaelisbihani ! Pourrais-tu me régénérer ce lien ?

**Comment by ColineLebaratoux** [comment]
Merci ! voilà mes retours :

- [ ] Est-ce que tu pourrais corriger l'interlignage entre le titre "choisissez la thématique de votre projet" et les cartes (prendre le même que celui de la question précédente) 
<img width="1297" alt="Capture d’écran 2024-07-23 à 16 45 11" src="https://github.com/user-attachments/assets/a8b75828-fd52-4be2-bac4-ef67009c0d5c">

- [ ] Ajouter ":" "choisissez la thématique de votre projet : "
<img width="466" alt="Capture d’écran 2024-07-23 à 16 48 28" src="https://github.com/user-attachments/assets/174c247f-38aa-437b-a825-c9d61926661e">


- [ ] Mettre en  [bleu roi](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6254%3A271572&t=9uAQA7VQBzecckHS-1)  le tiret et le contour du tag de la thématique économies d'eau 

- [ ] Revoir l'ordre d'affichage des cartes thématiques, en suivant celui de la maquette (c'est bizarre tu l'as coché dans la liste plus haut, mais ça n'a pas changé)

- [ ] Sur mobile (à partir du moment où la carte est sans l'image) Ajouter des couleurs de fond aux cartes [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6291-334718&t=h6Zdp2mCasexHUto-1)
<img width="240" alt="Capture d’écran 2024-07-23 à 16 50 31" src="https://github.com/user-attachments/assets/7476a575-f3fc-4deb-8343-f28e985966f2">

- [ ] Sur mobile, augmenter la taille des titres des cartes thématiques "Énergie" "Économies d'eau"...[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6291-334718&t=h6Zdp2mCasexHUto-1)

**Comment by oumeimaelisbihani** [comment]
Je mets ici les remarques de @ttdm, si tu veux bien donner ton avis @ColineLebaratoux  : 

- Je pense qu'il ne faut pas afficher les tags si aucune aide du projet n'est disponible (dans l'ex: construction&rénovation-> serres agricoles)

- En cliquant sur un tag, je m'attend à ce qu'il m'ammène directement sur le projet en question.

- J'avais fais une remarque un peu similaire sur l'autre parcours, mais je trouve ça vraiment étonnant d'afficher la thématique puis d'arriver sur une page "aucun projet éligible" (comme pour l'eau dans l'exemple). Peut être arriver directement sur les aides

**Comment by ColineLebaratoux** [comment]
- oui en effet, il faut unqiuement afficher les tags des projets "éligibles" pour l'entreprise. 
- les tags projets sont cliquables et doivent mener directement sur la fiche projet. Je pense que cette évolution est prévue sur ce ticket [#798](https://github.com/betagouv/mission-transition-ecologique/issues/798)
- Je me charge d'ajouter des projets supplémentaires à la thématique eau ! La prochaine évolution consistera à ajouter un [formulaire ](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=5974-316581&t=h6Zdp2mCasexHUto-1)à la suite des actions/message "aucune aide" pour proposer une solution, de repli à l'utilisateur

<img width="436" alt="Capture d’écran 2024-07-23 à 17 18 23" src="https://github.com/user-attachments/assets/bed00cad-3ede-4642-be1a-cab50d66a653">

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr856.osc-fr1.scalingo.io/ voila les modifications ! Pour le changement de couleur de l'eau ça se fera automatiquement au merge de l'autre branche spécifique

**Comment by ColineLebaratoux** [comment]
Merci Oumeima, 

- [ ]  Revoir l'ordre d'affichage des cartes thématiques, en suivant celui de la maquette (encore une fois ça n'a pas changé : bug ?)
<img width="347" alt="Capture d’écran 2024-07-24 à 16 19 16" src="https://github.com/user-attachments/assets/27104275-bc6f-453b-8e37-c9d31eda3bef">

- [ ] En augmentant la taille des titres sur les cartes, ça coupe le titre "analyses environnementales". Soit on baisse d'un point la taille du texte, on peut peut-être aussi diminuer l'espacement entre les cartes pour gagner en largeur ?
<img width="460" alt="Capture d’écran 2024-07-24 à 16 20 31" src="https://github.com/user-attachments/assets/ebc06124-8854-4115-9dcd-75867b53086c">

<img width="245" alt="Capture d’écran 2024-07-24 à 16 13 39" src="https://github.com/user-attachments/assets/b004ac2f-050e-4ef9-a5c4-e0116e17d422">

**Comment by oumeimaelisbihani** [comment]
c'est enfin bon : https://tee-preprod-pr856.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Top, merci ! 
Il reste juste un bug : 
Les tags sont passés vert sur les cartes jaunes
<img width="259" alt="Capture d’écran 2024-07-25 à 09 40 43" src="https://github.com/user-attachments/assets/
<img width="339" alt="Capture d’écran 2024-07-25 à 09 40 14" src="https://github.com/user-attachments/assets/95a60991-289e-4ca4-ba61-6b00bf0b572a">
bd20fb8d-f82b-4b86-89bd-27cfa0aa3b49">

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr856.osc-fr1.scalingo.io/ c'est réglé !
