### ISSUE TITLE
Supprimer les pistes de questions dans le fil d'étape du formulaire

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#800]
Irritant utilisateur : 
❌ Le fil d'ariane prend trop de place en longueur et n'est pas utilisé par les utilisateurs pour revenir sur chaque piste de question.
❌ Sa présence pose question “d’accord, je comprends pas trop l’interêt de ce truc. en fait ici, la liste de gauche (parle du fil d’ariane) j’avais pas compris ce que c’était. je pensais que c’etait un menu du site ou des filtres comme sur le site de la fnac par exemple. j’avais pas compris que c’etait pour revenir en arrière. c’est bizarre.”

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/cc12edfe-6b7f-4dee-8b17-7f2ccd6055d4)
---
TO DO 
- [ ]  Supprimer les pistes de questions sous les thématiques dans le questionnaire (pour alléger)
- [ ] Supprimer completement la premiere section "comment vous aider ?"
---

[maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6766-301813&t=W3eJy6NzjvQJ0VZG-1) 

<img width="663" alt="Capture d’écran 2024-08-30 à 10 38 48" src="https://github.com/user-attachments/assets/7296c979-57c5-4ded-9242-334fe5c96714">

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/105
```

**Comment by jbledevehat** [comment]
@ColineLebaratoux Maquette à ajouter stp

**Comment by yvalentin** [comment]
@ColineLebaratoux voici le lien pour la validation
https://tee-preprod-pr1087.osc-fr1.scalingo.io/
