### ISSUE TITLE
Supprimer la topbar sur les pages de résultatrs

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#871]
- [x] Supprimer la top-bar de la page de résultats (des 2 parcours). Elle n'apparaitra que sur la fiche produit et la fiche dispositif. 
Objectif : gagner de la place pour faire remonter les résultats plus haut. 

![Image](https://github.com/betagouv/mission-transition-ecologique/assets/47628484/bcb937c8-99bf-43a9-bee3-18c8049e48d1)

---
cible : 

![Image](https://github.com/user-attachments/assets/ff239608-1079-438a-b6fc-728c569f5669)

ticket lié : Intégrer le fil d'étape (fils d'ariane)
[#761](https://github.com/betagouv/mission-transition-ecologique/issues/761)
```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/761
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/869
```

**Comment by jbledevehat** [comment]
@oumeimaelisbihani peux-tu me générer le lien pour recetter stp ?

**Comment by oumeimaelisbihani** [comment]
https://tee-preprod-pr924.osc-fr1.scalingo.io/ c'est le même que pour le fil d'ariane, j'ai fais tout sur une même branche

**Comment by jbledevehat** [comment]
Ok c'est bon pour moi
