### ISSUE TITLE
[Layout]  Revoir les marges des cartes dispositifs sur la liste de résultats

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#906]
- [ ] ajouter des marges autour des cartes des dispositifs, comme pour les cartes projets (uniformisation)

![Image](https://github.com/user-attachments/assets/d1860b3e-79d0-4323-afcb-734b99e62ca4)

![Image](https://github.com/user-attachments/assets/ed568d80-074f-4132-9092-6632d5096936)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/868
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1152
```

**Comment by yvalentin** [comment]
@ColineLebaratoux 
https://tee-preprod-pr1875.osc-fr1.scalingo.io/
