### ISSUE TITLE
[XP Cannes] - Intégration des dispositifs locaux Région Sud, Arbe/OFB

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#934]
https://www.notion.so/accelerateur-transition-ecologique-ademe/BizDev-8a3fb1541b3443b792b6892fdfdaa675
```[tasklist]
### Tasks
- [x] Ajout des aides identifiées Région Sud + ARBE
- [x] Ajout d'une thématique biodiversité
- [x] Vérifier que les dispositifs du Fonds chaleur soient bien intégrés dans les projets
- [x] Relier les dispositifs Région Sud + ARBE aux projets existants sur baserow
```

**Comment by jbledevehat** [comment]
Voici la liste des actions FTD suite à réception et retraitement des données par l'équipe FTD : https://docs.google.com/spreadsheets/d/1LffE_GKtQG745Iyi9wnq8u8Vt12uu-AUd1FD_QajE90/edit?gid=484431621#gid=484431621

**Comment by mpiac** [comment]
Pour le Fonds Chaleur et l'articulation aides nationales/locales : à termes il faudrait pouvoir ajouter des éléments lorsque l'entreprise est domicilié dans tel ou tel endroit (via des colonnes sur baserow si Alpes-Maritime alors > étapes supplémentaires); 
Pour l'expé, on peut écrire directement dans les dispositifs Fonds Chaleur avec une mention 'si vous êtes dans le département des Alpes-Maritimes' alors : 
1. Réalisez une note d'opportunité gratuite avec des référents techniques qui se déplacent pour évaluer la pertinence, le type d'énergie à mobiliser et vous aider à la décision 
2. Bénéficier d'une aide à la commande d'une étude de faisabilité conforme : Accompagnement dans la recherche d'un prestataire et aide au montage du dossier.

**Comment by mpiac** [comment]
On aussi ce guidé ademe pour info : https://www.monreseaupro-pnrsud.fr/media/uploads/2022/03/hebergeurs-touristiques-quelles-actions-mettre-en-place-pour-un-tourisme-durable-ademe.pdf

**Comment by mpiac** [comment]
Sur les typologies d'aide : dans quelle typologie intégrer les chartes/les écodéfis aussi ? Labels pour écodéfi/clef verte? Valorisation ? idée d'appartenir à une communauté, de s'engager sur des actions etc.

**Comment by jbledevehat** [comment]
Je me suis permis de modifier la carte pour distinguer le travail d'ajout des aides (ici) et celui d'ajouter des projets - voir #909

**Comment by jbledevehat** [comment]
PR : https://tee-preprod-pr1095.osc-fr1.scalingo.io/questionnaire/resultat?choix-du-parcours=j-ai-un-projet&siret=90540811800024&effectif=PE&objectifs=building
