### ISSUE TITLE
[XP Cannes] - Organisation événement opérateurs publics 17 décembre

### ISSUE THREAD

**Issue by celinebagault** [betagouv/mission-transition-ecologique#936]
https://www.notion.so/accelerateur-transition-ecologique-ademe/Atelier-op-rateurs-PACA-fin-2024-1296523d57d780ed8751d32c17049fa8
```[tasklist]
### Tasks
- [x] Trouver une date commune pour un atelier opérateurs publics fin d'année
- [x] Faire une liste des hypothèses à valider
- [x] En présentiel ou distanciel ?
- [ ] Quelles sont les mesures d'impact sur cette expérimentation
- [ ] Faire une présentation
```
