### ISSUE TITLE
Parcours compléter son profil entreprise sur un projet

### ISSUE THREAD

**Issue by jbledevehat** [betagouv/mission-transition-ecologique#941]
Comment faciliter la navigation entre les différents parcours du site ? 
Sujet de la persistance des données utilisateurs ? (sauvegarder le siret, effectif sur l'ensemble des parcours)

- [ ] Parcours 1 : En tant qu'utilisateur, je n'ai pas fait le parcours "Je ne sais pas..." ni "J'ai un projet en tête". J'arrive directement sur le catalogue projet. Je choisi un projet dans le catalogue des projets. Je dois compléter mon profil. 
   - Je saisie les données sur mon entreprise SIRET / Taille ou manuellement Taille / Activités / Régions > Et je retourne sur la fiche projet que j'avais séléctionné (sans définir l'objectif comme actuellement...)
       - Soit j'ai des aides, j'ai les aides qui me concerne
       - Soit je n'ai pas d'aides dans mon cas, et je n'ai pas de bloc aides
   - Objectif : Ne pas avoir à refaire un parcours pour voir si un projet est éligible à une entreprises
   - Erreur UX : J'ai vu un projet dans l'annuaire, après complétude aujourd'hui je ne revois pas le projet en résultat (exemple : éclairage LED) 
- [ ] Parcours 2 : En tant qu'utilisateur, j'ai fait le parcours "Je ne sais pas..." ou "J'ai un projet en tête". J'arrive sur le catalogue projet. Je choisi un projet dans le catalogue des projets. Je n'ai pas de message de "Complétez votre profil en 2 minutes"
   - Soit j'ai des aides, j'ai les aides qui me concerne
   - Soit je n'ai pas d'aides dans mon cas, et je n'ai pas de bloc aides
   - Objectif : Conserver les informations sur l'entreprise entre les différents parcours

---
vision cible 
- Compte utilisateur ?  (Mini compte avec les données entreprise + Instruction minimal du dossier : "votre demande est en cours / transmise" ...
- Un bandeau persistant sur l'ensemble du site comme Clic’agil ? 

--
virer les formulaires de contact ? 
s'inspirer de ["vérifier min éligibilité"](https://pacte-industrie.ademe.fr/solutions/developper-sa-strategie-de-decarbonation-act-pas-a-pas)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/787
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/867
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/977
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/1101
```

**Comment by jbledevehat** [comment]
poke @ColineLebaratoux pour review UX

**Comment by ColineLebaratoux** [comment]
@ColineLebaratoux @jbledevehat remarques de @ttdm, peut etre à réfléchir dans un prochain ticket :

- si une entreprise passe par j'ai un projet en tête puis retourne sur l'annuaire alors elle va voir le bandeau. ça peut être surprenant comme information pour cette entreprise puisqu'elle a déjà renseigné ses informations.

- J'ai l'impression qu'à la place du bandeau, il lui faudrait une information discrète d'élligibilité sur la page. J'imagine un petit encart en couleur, d'après les informations transmises, vous êtes éligibible ou non à cette aide. Plus une deuxième ligne qui explique que tous les dispositifs sont affichés sur le catalogue et qu'en suivant un lien, l'entreprise ne verra alors que les projets auxquelle elle est éligible.
