### ISSUE TITLE
Création calendrier stratégie de communication

### ISSUE THREAD

**Issue by oumeimaelisbihani** [betagouv/mission-transition-ecologique#950]
```[tasklist]
### Tasks
- [x] Faire une première ébauche sur Notion pour la définition du plan de com : https://www.notion.so/accelerateur-transition-ecologique-ademe/Plan-de-communication-40bc190660c64873902aad26c4b0a2a6?p=7b2e2e859e904bae90afdf782d8b1381&pm=s
- [x] Organiser un point d'équipe le mardi 27/08
- [x] Programmer calendrier et board Rodolphe
```

**Comment by RodolpheGagetta** [comment]
rattaché à #1036
