### ISSUE TITLE
Appel des 10 entreprises fin de l'histoire

### ISSUE THREAD

**Issue by oumeimaelisbihani** [betagouv/mission-transition-ecologique#952]
```[tasklist]
### Tasks
- [x] test qualitatif : tri de dix besoins pour rappeler les chefs d’entreprise et connaître la fin de l’histoire
- [ ] rappel de ces dix entreprises (Céline/Manon/Rodolphe) : 7 entreprises au 13082024
- [ ] Restitution fin de l'histoire le 3 septembre
```
