### ISSUE TITLE
corrections UX UI sur les catalogues

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#959]
- [ ] Sur le catalogue des projets, supprimer la mention "Quel est votre projet ?" 

![Image](https://github.com/user-attachments/assets/f018974f-1770-428d-b402-8a2ebf5f5314)

---

- [ ] Sur les 2 catalogues, réduire l'espacement entre le bandeau thématique et les tags (et harmoniser cet espacement sur les 2 catalogues ainsi que les pages de résultats)

![Image](https://github.com/user-attachments/assets/cdcbc029-3616-4439-975f-803c257e4d1e)

[cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6799-392260&t=zEDuteRH8167Djhy-1)
![Image](https://github.com/user-attachments/assets/80525871-d1fe-4585-ad2b-0411de935b09)

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/792
```

**Comment by dolemoine** [comment]
désolé @ColineLebaratoux j'ai oublié de te fournir le lien pour vérification : https://tee-preprod-pr1028.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Parfait, merci ! Je me permets d'ajouter une autre modif UI sur cette page : 

- [ ] Harmoniser les espacements entre le catalogue projets et aides au niveau de la mention du nombre de résultats et de la liste des résultats 

![Capture d’écran 2024-09-03 à 11 16 50](https://github.com/user-attachments/assets/4a949c4e-fa5d-41d4-881d-c0e201da36cf)

appliquer le même espacement que sur le catalogue des aides : 
![Capture d’écran 2024-09-03 à 11 17 32](https://github.com/user-attachments/assets/cab8cb28-3666-4848-918f-5e01302b6ad6)

**Comment by dolemoine** [comment]
@ColineLebaratoux, j'ai apporté les modifs https://tee-preprod-pr1028.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
@dolemoine c'est étrange, je ne vois pas la correction. J'ai essayé sur 2 navigateurs et j'ai supprimé mes données de navigation.

**Comment by dolemoine** [comment]
@ColineLebaratoux oui tu as raison, le déploiement ne s'est pas fait, ça devrait être bon maintenant: https://tee-preprod-pr1028.osc-fr1.scalingo.io/
