### ISSUE TITLE
Correction fil d'arianne

### ISSUE THREAD

**Issue by ColineLebaratoux** [betagouv/mission-transition-ecologique#970]
Correction suite à l'intégration du fil d'ariane : 

- [ ] Diminuer l'espacement entre le fil d'ariane et le contenu de la page = [cf maquette](https://www.figma.com/design/tHgzORFkJYTVspsQgR2kg6/TEE-V5?node-id=6799-464423&t=lWgzFmyvBexq2FIo-1)

![Image](https://github.com/user-attachments/assets/c133bfaf-5a30-4c75-b645-1ae662944a21)

- [ ] ajouter le fil d'arianne sur les pages catalogues 

```[tasklist]
### Tasks
- [ ] https://github.com/betagouv/mission-transition-ecologique/issues/761
```

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux >> https://tee-preprod-pr1019.osc-fr1.scalingo.io/

**Comment by yvalentin** [comment]
@ColineLebaratoux @jbledevehat @oumeimaelisbihani 
Il semble qu'il manque des pages avec le fils d'ariane. Exemple sur les page statiques comme :
- https://mission-transition-ecologique.beta.gouv.fr/stats

Dans le ticket initial #761 il est indiqué:
> Afficher sur toutes les pages sauf les pistes de questions

Quand pensez-vous ?

Pour moi, les pages qui ne doivent pas contenir de fil d'ariane sont :
- https://mission-transition-ecologique.beta.gouv.fr/echanger-avec-un-conseiller
- https://mission-transition-ecologique.beta.gouv.fr/questionnaire (toute la piste de question)

**Comment by ColineLebaratoux** [comment]
@yvalentin @oumeimaelisbihani 

- [ ] Bien vu, il manque le fil d'ariane sur la page stats.

Les pages qui ne doivent pas contenir de fil d'ariane sont :

- https://mission-transition-ecologique.beta.gouv.fr/echanger-avec-un-conseiller
- https://mission-transition-ecologique.beta.gouv.fr/questionnaire (toute la piste de question)
- https://mission-transition-ecologique.beta.gouv.fr/

- [ ] ça m'a permis de remarquer une autre correction sur le placement du fil d'ariane sur les 2 pages catalogues. Il doit être situé au dessus du bandeau de titre, aligné sur la colonne de gauche. 

![Capture d’écran 2024-08-28 à 15 02 20](https://github.com/user-attachments/assets/2df65e80-dabc-4b42-a1e3-67d1c2777eb9)
comme sur les fiches projets :
![Capture d’écran 2024-08-28 à 15 08 44](https://github.com/user-attachments/assets/0e356a32-7452-4e82-95b5-f67e37439162)

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux >> nouveau test là https://tee-preprod-pr1019.osc-fr1.scalingo.io/, l'ajout du breacrumb a été fait sur : catalogues projets + programs + page legale + page statistique + page données perso + page accessibilité

**Comment by ColineLebaratoux** [comment]
@oumeimaelisbihani il y avait aussi une correction de placement du fil d'ariane au dessus du bandeau de titre des catalogues.
<img width="1437" alt="Capture d’écran 2024-08-30 à 11 53 41" src="https://github.com/user-attachments/assets/c5fc7040-59f1-45aa-903f-e6c89ead1b36">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux c'est modifié : https://tee-preprod-pr1019.osc-fr1.scalingo.io/

**Comment by ColineLebaratoux** [comment]
Merci @oumeimaelisbihani 
Tu peux aussi modifier le placement sur les pages du footer 
<img width="1440" alt="Capture d’écran 2024-09-02 à 11 42 01" src="https://github.com/user-attachments/assets/b9ad4a9d-4abc-4624-a5c9-a1a6eb429d0c">

comme celui que tu as fait sur les pages catalogues
<img width="849" alt="Capture d’écran 2024-09-02 à 11 42 08" src="https://github.com/user-attachments/assets/d50567a9-01b1-4bd1-acbf-9277abd3a4a0">

**Comment by oumeimaelisbihani** [comment]
@ColineLebaratoux https://tee-preprod-pr1019.osc-fr1.scalingo.io/ , est ce que je laisse l'espacement entre le titre de la page statique et le fil d'ariane ?

**Comment by ColineLebaratoux** [comment]
hello @oumeimaelisbihani ! oui tu peux remonter le titre plus proche du fil d'ariane
