### ISSUE TITLE
Ajouter une thématique biodiversité

### ISSUE THREAD

**Issue by mpiac** [betagouv/mission-transition-ecologique#985]
```[tasklist]
### Tasks
- [x] Ajouter une thématique biodiversité sur baserow
- [x] Vérifier les dispositifs actuels que nous pourrions étiqueter dans biodiversité @mpiac
- [x] Réaliser l'illustration Biodiversité @ColineLebaratoux
- [x] Mettre à jour l'illustration biodiv sur les bandeaux thématiques et cartes thématiques, icône "abeille" fond couleur vert @ttdm
- [x] En profiter pour mettre à jour l'illustration "Eau" @ttdm
```
![Image](https://github.com/user-attachments/assets/852410bf-1356-4fd7-b548-a972bb363105)
![Image](https://github.com/user-attachments/assets/1b50e2cf-56d7-4626-9179-890492247381)

**Comment by ColineLebaratoux** [comment]
@ttdm en effectuant le changement d'illustrations pour les thématiques biodiv et eau, il semblerait que les tailels des bandeaux & images ont bougé, cf [écran "mon projet"](https://mission-transition-ecologique.beta.gouv.fr/questionnaire/objectifs?choix-du-parcours=j-ai-un-projet&siret=44474511100021&effectif=ETI_GE#questionnaire)
![Image](https://github.com/user-attachments/assets/9876d806-7da3-4720-a2ee-2a67440c5c7d)

Par ailleurs, les vecteurs de mon illu sur l'économies d'eau semble cassés, je te remets un nouveau svg ici pour le remplacer. 
![Image](https://github.com/user-attachments/assets/f944f9d6-7549-4fdc-b97a-492e007e511e)

Merci !

**Comment by ColineLebaratoux** [comment]
hello @mpiac ! Ce ticket est terminé ?

**Comment by mpiac** [comment]
Non je dois encore faire une passe sur les 100 dispositifs pour checker.
